package com.medical.dao;

import com.medical.model.CurrectChronic;
import com.medical.model.CurrectChronicExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CurrectChronicDAOImpl extends SqlMapClientDaoSupport implements CurrectChronicDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.CURRECT_CHRONIC
	 * @ibatorgenerated  Fri Oct 31 11:26:08 CST 2014
	 */
	public CurrectChronicDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.CURRECT_CHRONIC
	 * @ibatorgenerated  Fri Oct 31 11:26:08 CST 2014
	 */
	public int countByExample(CurrectChronicExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"CURRECT_CHRONIC.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.CURRECT_CHRONIC
	 * @ibatorgenerated  Fri Oct 31 11:26:08 CST 2014
	 */
	public int deleteByExample(CurrectChronicExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"CURRECT_CHRONIC.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.CURRECT_CHRONIC
	 * @ibatorgenerated  Fri Oct 31 11:26:08 CST 2014
	 */
	public void insert(CurrectChronic record) {
		getSqlMapClientTemplate().insert(
				"CURRECT_CHRONIC.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.CURRECT_CHRONIC
	 * @ibatorgenerated  Fri Oct 31 11:26:08 CST 2014
	 */
	public void insertSelective(CurrectChronic record) {
		getSqlMapClientTemplate().insert(
				"CURRECT_CHRONIC.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.CURRECT_CHRONIC
	 * @ibatorgenerated  Fri Oct 31 11:26:08 CST 2014
	 */
	@SuppressWarnings("unchecked") public List<CurrectChronic> selectByExample(CurrectChronicExample example){List<CurrectChronic> list=getSqlMapClientTemplate().queryForList("CURRECT_CHRONIC.ibatorgenerated_selectByExample",example);return list;}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.CURRECT_CHRONIC
	 * @ibatorgenerated  Fri Oct 31 11:26:08 CST 2014
	 */
	public int updateByExampleSelective(CurrectChronic record,
			CurrectChronicExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"CURRECT_CHRONIC.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.CURRECT_CHRONIC
	 * @ibatorgenerated  Fri Oct 31 11:26:08 CST 2014
	 */
	public int updateByExample(CurrectChronic record,
			CurrectChronicExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"CURRECT_CHRONIC.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table YLJZN.CURRECT_CHRONIC
	 * @ibatorgenerated  Fri Oct 31 11:26:08 CST 2014
	 */
	private static class UpdateByExampleParms extends CurrectChronicExample {
		private Object record;

		public UpdateByExampleParms(Object record, CurrectChronicExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}