package com.medical.dao;

import com.medical.model.DmBizdept;
import com.medical.model.DmBizdeptExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DmBizdeptDAOImpl extends SqlMapClientDaoSupport implements DmBizdeptDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public DmBizdeptDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public int countByExample(DmBizdeptExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("DM_BIZDEPT.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public int deleteByExample(DmBizdeptExample example) {
        int rows = getSqlMapClientTemplate().delete("DM_BIZDEPT.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public int deleteByPrimaryKey(String hospitalId) {
        DmBizdept key = new DmBizdept();
        key.setHospitalId(hospitalId);
        int rows = getSqlMapClientTemplate().delete("DM_BIZDEPT.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public void insert(DmBizdept record) {
        getSqlMapClientTemplate().insert("DM_BIZDEPT.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public void insertSelective(DmBizdept record) {
        getSqlMapClientTemplate().insert("DM_BIZDEPT.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    @SuppressWarnings("unchecked")
    public List<DmBizdept> selectByExample(DmBizdeptExample example) {
        List<DmBizdept> list = getSqlMapClientTemplate().queryForList("DM_BIZDEPT.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public DmBizdept selectByPrimaryKey(String hospitalId) {
        DmBizdept key = new DmBizdept();
        key.setHospitalId(hospitalId);
        DmBizdept record = (DmBizdept) getSqlMapClientTemplate().queryForObject("DM_BIZDEPT.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public int updateByExampleSelective(DmBizdept record, DmBizdeptExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("DM_BIZDEPT.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public int updateByExample(DmBizdept record, DmBizdeptExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("DM_BIZDEPT.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public int updateByPrimaryKeySelective(DmBizdept record) {
        int rows = getSqlMapClientTemplate().update("DM_BIZDEPT.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public int updateByPrimaryKey(DmBizdept record) {
        int rows = getSqlMapClientTemplate().update("DM_BIZDEPT.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table YLJZN.DM_BIZDEPT
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    private static class UpdateByExampleParms extends DmBizdeptExample {
        private Object record;

        public UpdateByExampleParms(Object record, DmBizdeptExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}