package com.medical.dao;

import com.medical.model.JzAct;
import com.medical.model.JzActExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzActDAOImpl extends SqlMapClientDaoSupport implements JzActDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public JzActDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public int countByExample(JzActExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"JZ_ACT.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public int deleteByExample(JzActExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"JZ_ACT.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public int deleteByPrimaryKey(Integer actId) {
		JzAct key = new JzAct();
		key.setActId(actId);
		int rows = getSqlMapClientTemplate().delete(
				"JZ_ACT.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public Integer insert(JzAct record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_ACT.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public Integer insertSelective(JzAct record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_ACT.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	@SuppressWarnings("unchecked")
	public List<JzAct> selectByExample(JzActExample example) {
		List<JzAct> list = getSqlMapClientTemplate().queryForList(
				"JZ_ACT.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public JzAct selectByPrimaryKey(Integer actId) {
		JzAct key = new JzAct();
		key.setActId(actId);
		JzAct record = (JzAct) getSqlMapClientTemplate().queryForObject(
				"JZ_ACT.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public int updateByExampleSelective(JzAct record, JzActExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_ACT.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public int updateByExample(JzAct record, JzActExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_ACT.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public int updateByPrimaryKeySelective(JzAct record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_ACT.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public int updateByPrimaryKey(JzAct record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_ACT.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table YLJZN.JZ_ACT
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private static class UpdateByExampleParms extends JzActExample {
		private Object record;

		public UpdateByExampleParms(Object record, JzActExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}