package com.medical.dao;

import com.medical.model.JzAnnex;
import com.medical.model.JzAnnexExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzAnnexDAOImpl extends SqlMapClientDaoSupport implements JzAnnexDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public JzAnnexDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public int countByExample(JzAnnexExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("JZ_ANNEX.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public int deleteByExample(JzAnnexExample example) {
        int rows = getSqlMapClientTemplate().delete("JZ_ANNEX.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public int deleteByPrimaryKey(Long annexId) {
        JzAnnex key = new JzAnnex();
        key.setAnnexId(annexId);
        int rows = getSqlMapClientTemplate().delete("JZ_ANNEX.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public Long insert(JzAnnex record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_ANNEX.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public Long insertSelective(JzAnnex record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_ANNEX.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<JzAnnex> selectByExample(JzAnnexExample example) {
        List<JzAnnex> list = getSqlMapClientTemplate().queryForList("JZ_ANNEX.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public JzAnnex selectByPrimaryKey(Long annexId) {
        JzAnnex key = new JzAnnex();
        key.setAnnexId(annexId);
        JzAnnex record = (JzAnnex) getSqlMapClientTemplate().queryForObject("JZ_ANNEX.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public int updateByExampleSelective(JzAnnex record, JzAnnexExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_ANNEX.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public int updateByExample(JzAnnex record, JzAnnexExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_ANNEX.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public int updateByPrimaryKeySelective(JzAnnex record) {
        int rows = getSqlMapClientTemplate().update("JZ_ANNEX.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    public int updateByPrimaryKey(JzAnnex record) {
        int rows = getSqlMapClientTemplate().update("JZ_ANNEX.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table YLJZN.JZ_ANNEX
     *
     * @ibatorgenerated Tue Jun 22 09:39:18 CST 2010
     */
    private static class UpdateByExampleParms extends JzAnnexExample {
        private Object record;

        public UpdateByExampleParms(Object record, JzAnnexExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}