package com.medical.dao;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.medical.model.JzAspapprove;
import com.medical.model.JzAspapproveExample;

public class JzAspapproveDAOImpl extends SqlMapClientDaoSupport implements JzAspapproveDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public JzAspapproveDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public int countByExample(JzAspapproveExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"JZ_ASPAPPROVE.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public int deleteByExample(JzAspapproveExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"JZ_ASPAPPROVE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public int deleteByPrimaryKey(BigDecimal aspapproveId) {
		JzAspapprove key = new JzAspapprove();
		key.setAspapproveId(aspapproveId);
		int rows = getSqlMapClientTemplate().delete(
				"JZ_ASPAPPROVE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public BigDecimal insert(JzAspapprove record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_ASPAPPROVE.ibatorgenerated_insert", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public BigDecimal insertSelective(JzAspapprove record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_ASPAPPROVE.ibatorgenerated_insertSelective", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<JzAspapprove> selectByExample(JzAspapproveExample example) {
		List<JzAspapprove> list = getSqlMapClientTemplate().queryForList(
				"JZ_ASPAPPROVE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public JzAspapprove selectByPrimaryKey(BigDecimal aspapproveId) {
		JzAspapprove key = new JzAspapprove();
		key.setAspapproveId(aspapproveId);
		JzAspapprove record = (JzAspapprove) getSqlMapClientTemplate()
				.queryForObject(
						"JZ_ASPAPPROVE.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public int updateByExampleSelective(JzAspapprove record,
			JzAspapproveExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"JZ_ASPAPPROVE.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public int updateByExample(JzAspapprove record, JzAspapproveExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_ASPAPPROVE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public int updateByPrimaryKeySelective(JzAspapprove record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_ASPAPPROVE.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public int updateByPrimaryKey(JzAspapprove record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_ASPAPPROVE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table YLJZN.JZ_ASPAPPROVE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private static class UpdateByExampleParms extends JzAspapproveExample {
		private Object record;

		public UpdateByExampleParms(Object record, JzAspapproveExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}

	@SuppressWarnings("unchecked")
	public List<JzAspapprove> selectByExample(JzAspapproveExample example,
			int start, int pagesize) {
		List<JzAspapprove> list = getSqlMapClientTemplate().queryForList(
				"JZ_ASPAPPROVE.ibatorgenerated_selectByExample", example,
				start, pagesize);
		return list;
	}
}