package com.medical.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.medical.model.JzBizHistory;
import com.medical.model.JzBizHistoryExample;

public class JzBizHistoryDAOImpl extends SqlMapClientDaoSupport implements
		JzBizHistoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public JzBizHistoryDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public int countByExample(JzBizHistoryExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public int deleteByExample(JzBizHistoryExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public int deleteByPrimaryKey(Integer jbhId) {
		JzBizHistory key = new JzBizHistory();
		key.setJbhId(jbhId);
		int rows = getSqlMapClientTemplate().delete(
				"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public void insert(JzBizHistory record) {
		getSqlMapClientTemplate().insert(
				"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public void insertSelective(JzBizHistory record) {
		getSqlMapClientTemplate().insert(
				"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<JzBizHistory> selectByExample(JzBizHistoryExample example) {
		List<JzBizHistory> list = getSqlMapClientTemplate()
				.queryForList(
						"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public JzBizHistory selectByPrimaryKey(Integer jbhId) {
		JzBizHistory key = new JzBizHistory();
		key.setJbhId(jbhId);
		JzBizHistory record = (JzBizHistory) getSqlMapClientTemplate()
				.queryForObject(
						"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public int updateByExampleSelective(JzBizHistory record,
			JzBizHistoryExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public int updateByExample(JzBizHistory record, JzBizHistoryExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public int updateByPrimaryKeySelective(JzBizHistory record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	public int updateByPrimaryKey(JzBizHistory record) {
		int rows = getSqlMapClientTemplate().update(
				"YLJZN_JZ_BIZ_HISTORY.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds
	 * to the database table YLJZN.JZ_BIZ_HISTORY
	 * 
	 * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
	 */
	private static class UpdateByExampleParms extends JzBizHistoryExample {
		private Object record;

		public UpdateByExampleParms(Object record, JzBizHistoryExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}