package com.medical.dao;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.medical.model.JzBizcheck;
import com.medical.model.JzBizcheckExample;

public class JzBizcheckDAOImpl extends SqlMapClientDaoSupport implements JzBizcheckDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public JzBizcheckDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public int countByExample(JzBizcheckExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"JZ_BIZCHECK.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public int deleteByExample(JzBizcheckExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"JZ_BIZCHECK.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public int deleteByPrimaryKey(BigDecimal bizcheckId) {
		JzBizcheck key = new JzBizcheck();
		key.setBizcheckId(bizcheckId);
		int rows = getSqlMapClientTemplate().delete(
				"JZ_BIZCHECK.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public BigDecimal insert(JzBizcheck record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_BIZCHECK.ibatorgenerated_insert", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public BigDecimal insertSelective(JzBizcheck record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_BIZCHECK.ibatorgenerated_insertSelective", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<JzBizcheck> selectByExample(JzBizcheckExample example) {
		List<JzBizcheck> list = getSqlMapClientTemplate().queryForList(
				"JZ_BIZCHECK.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public JzBizcheck selectByPrimaryKey(BigDecimal bizcheckId) {
		JzBizcheck key = new JzBizcheck();
		key.setBizcheckId(bizcheckId);
		JzBizcheck record = (JzBizcheck) getSqlMapClientTemplate()
				.queryForObject(
						"JZ_BIZCHECK.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public int updateByExampleSelective(JzBizcheck record,
			JzBizcheckExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public int updateByExample(JzBizcheck record, JzBizcheckExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public int updateByPrimaryKeySelective(JzBizcheck record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	public int updateByPrimaryKey(JzBizcheck record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	private static class UpdateByExampleParms extends JzBizcheckExample {
		private Object record;

		public UpdateByExampleParms(Object record, JzBizcheckExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}