package com.medical.dao;

import com.medical.model.JzBizcheck;
import com.medical.model.JzBizcheckExample;
import java.math.BigDecimal;
import java.util.List;

public interface JzBizcheckDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	int countByExample(JzBizcheckExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	int deleteByExample(JzBizcheckExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	int deleteByPrimaryKey(BigDecimal bizcheckId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	BigDecimal insert(JzBizcheck record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	BigDecimal insertSelective(JzBizcheck record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	List<JzBizcheck> selectByExample(JzBizcheckExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	JzBizcheck selectByPrimaryKey(BigDecimal bizcheckId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	int updateByExampleSelective(JzBizcheck record, JzBizcheckExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	int updateByExample(JzBizcheck record, JzBizcheckExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	int updateByPrimaryKeySelective(JzBizcheck record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_BIZCHECK
	 * @ibatorgenerated  Thu Aug 27 16:02:15 CST 2009
	 */
	int updateByPrimaryKey(JzBizcheck record);
}