package com.medical.dao;

import com.medical.model.JzChronicapprove;
import com.medical.model.JzChronicapproveExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzChronicapproveDAOImpl extends SqlMapClientDaoSupport implements
		JzChronicapproveDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public JzChronicapproveDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public int countByExample(JzChronicapproveExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"JZ_CHRONICAPPROVE.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public int deleteByExample(JzChronicapproveExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"JZ_CHRONICAPPROVE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public int deleteByPrimaryKey(BigDecimal chronicapproveId) {
		JzChronicapprove key = new JzChronicapprove();
		key.setChronicapproveId(chronicapproveId);
		int rows = getSqlMapClientTemplate().delete(
				"JZ_CHRONICAPPROVE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public BigDecimal insert(JzChronicapprove record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_CHRONICAPPROVE.ibatorgenerated_insert", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public BigDecimal insertSelective(JzChronicapprove record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_CHRONICAPPROVE.ibatorgenerated_insertSelective", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	@SuppressWarnings("unchecked") public List<JzChronicapprove> selectByExample(JzChronicapproveExample example){List<JzChronicapprove> list=getSqlMapClientTemplate().queryForList("JZ_CHRONICAPPROVE.ibatorgenerated_selectByExample",example);return list;}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public JzChronicapprove selectByPrimaryKey(BigDecimal chronicapproveId) {
		JzChronicapprove key = new JzChronicapprove();
		key.setChronicapproveId(chronicapproveId);
		JzChronicapprove record = (JzChronicapprove) getSqlMapClientTemplate()
				.queryForObject(
						"JZ_CHRONICAPPROVE.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public int updateByExampleSelective(JzChronicapprove record,
			JzChronicapproveExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_CHRONICAPPROVE.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public int updateByExample(JzChronicapprove record,
			JzChronicapproveExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_CHRONICAPPROVE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public int updateByPrimaryKeySelective(JzChronicapprove record) {
		int rows = getSqlMapClientTemplate()
				.update("JZ_CHRONICAPPROVE.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	public int updateByPrimaryKey(JzChronicapprove record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_CHRONICAPPROVE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table YLJZN.JZ_CHRONICAPPROVE
	 * @ibatorgenerated  Mon Oct 27 15:50:27 CST 2014
	 */
	private static class UpdateByExampleParms extends JzChronicapproveExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				JzChronicapproveExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@SuppressWarnings("unchecked")
	public List<JzChronicapprove> selectByExample(
			JzChronicapproveExample example, int skipResults, int maxResults) {
		List<JzChronicapprove> list = getSqlMapClientTemplate().queryForList(
				"JZ_CHRONICAPPROVE.ibatorgenerated_selectByExample", example,
				skipResults, maxResults);
		return list;
	}
}