package com.medical.dao;

import com.medical.model.JzChronicbillemploy;
import com.medical.model.JzChronicbillemployExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzChronicbillemployDAOImpl extends SqlMapClientDaoSupport implements JzChronicbillemployDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_CHRONICBILLEMPLOY
     *
     * @ibatorgenerated Mon Aug 25 15:09:07 CST 2014
     */
    public JzChronicbillemployDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_CHRONICBILLEMPLOY
     *
     * @ibatorgenerated Mon Aug 25 15:09:07 CST 2014
     */
    public int countByExample(JzChronicbillemployExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("JZ_CHRONICBILLEMPLOY.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_CHRONICBILLEMPLOY
     *
     * @ibatorgenerated Mon Aug 25 15:09:07 CST 2014
     */
    public int deleteByExample(JzChronicbillemployExample example) {
        int rows = getSqlMapClientTemplate().delete("JZ_CHRONICBILLEMPLOY.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_CHRONICBILLEMPLOY
     *
     * @ibatorgenerated Mon Aug 25 15:09:07 CST 2014
     */
    public String insert(JzChronicbillemploy record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_CHRONICBILLEMPLOY.ibatorgenerated_insert", record);
        return (String) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_CHRONICBILLEMPLOY
     *
     * @ibatorgenerated Mon Aug 25 15:09:07 CST 2014
     */
    public String insertSelective(JzChronicbillemploy record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_CHRONICBILLEMPLOY.ibatorgenerated_insertSelective", record);
        return (String) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_CHRONICBILLEMPLOY
     *
     * @ibatorgenerated Mon Aug 25 15:09:07 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<JzChronicbillemploy> selectByExample(JzChronicbillemployExample example) {
        List<JzChronicbillemploy> list = getSqlMapClientTemplate().queryForList("JZ_CHRONICBILLEMPLOY.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_CHRONICBILLEMPLOY
     *
     * @ibatorgenerated Mon Aug 25 15:09:07 CST 2014
     */
    public int updateByExampleSelective(JzChronicbillemploy record, JzChronicbillemployExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_CHRONICBILLEMPLOY.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_CHRONICBILLEMPLOY
     *
     * @ibatorgenerated Mon Aug 25 15:09:07 CST 2014
     */
    public int updateByExample(JzChronicbillemploy record, JzChronicbillemployExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_CHRONICBILLEMPLOY.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table YLJZN.JZ_CHRONICBILLEMPLOY
     *
     * @ibatorgenerated Mon Aug 25 15:09:07 CST 2014
     */
    private static class UpdateByExampleParms extends JzChronicbillemployExample {
        private Object record;

        public UpdateByExampleParms(Object record, JzChronicbillemployExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}