package com.medical.dao;

import com.medical.model.JzManual;
import com.medical.model.JzManualExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzManualDAOImpl extends SqlMapClientDaoSupport implements JzManualDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public JzManualDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public int countByExample(JzManualExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"JZ_MANUAL.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public int deleteByExample(JzManualExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"JZ_MANUAL.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public int deleteByPrimaryKey(Long manualId) {
		JzManual key = new JzManual();
		key.setManualId(manualId);
		int rows = getSqlMapClientTemplate().delete(
				"JZ_MANUAL.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Long insert(JzManual record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_MANUAL.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Long insertSelective(JzManual record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_MANUAL.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<JzManual> selectByExample(JzManualExample example) {
		List<JzManual> list = getSqlMapClientTemplate().queryForList(
				"JZ_MANUAL.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public JzManual selectByPrimaryKey(Long manualId) {
		JzManual key = new JzManual();
		key.setManualId(manualId);
		JzManual record = (JzManual) getSqlMapClientTemplate().queryForObject(
				"JZ_MANUAL.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public int updateByExampleSelective(JzManual record, JzManualExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_MANUAL.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public int updateByExample(JzManual record, JzManualExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_MANUAL.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public int updateByPrimaryKeySelective(JzManual record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"JZ_MANUAL.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public int updateByPrimaryKey(JzManual record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_MANUAL.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table YLJZN.JZ_MANUAL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private static class UpdateByExampleParms extends JzManualExample {
		private Object record;

		public UpdateByExampleParms(Object record, JzManualExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}