package com.medical.dao;

import com.medical.model.JzPaylist;
import com.medical.model.JzPaylistExample;
import java.util.List;

public interface JzPaylistDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    int countByExample(JzPaylistExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    int deleteByExample(JzPaylistExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    int deleteByPrimaryKey(Integer paylistId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    Integer insert(JzPaylist record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    Integer insertSelective(JzPaylist record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    List<JzPaylist> selectByExample(JzPaylistExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    JzPaylist selectByPrimaryKey(Integer paylistId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    int updateByExampleSelective(JzPaylist record, JzPaylistExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    int updateByExample(JzPaylist record, JzPaylistExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    int updateByPrimaryKeySelective(JzPaylist record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.JZ_PAYLIST
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    int updateByPrimaryKey(JzPaylist record);
}