package com.medical.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.medical.model.MemberBaseinfo;
import com.medical.model.MemberBaseinfoExample;

public class MemberBaseinfoDAOImpl extends SqlMapClientDaoSupport implements
		MemberBaseinfoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.MEMBER_BASEINFO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public MemberBaseinfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.MEMBER_BASEINFO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public int countByExample(MemberBaseinfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"MEMBER_BASEINFO.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.MEMBER_BASEINFO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public int deleteByExample(MemberBaseinfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"MEMBER_BASEINFO.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.MEMBER_BASEINFO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void insert(MemberBaseinfo record) {
		getSqlMapClientTemplate().insert(
				"MEMBER_BASEINFO.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.MEMBER_BASEINFO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void insertSelective(MemberBaseinfo record) {
		getSqlMapClientTemplate().insert(
				"MEMBER_BASEINFO.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.MEMBER_BASEINFO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	@SuppressWarnings("unchecked")
	public List<MemberBaseinfo> selectByExample(MemberBaseinfoExample example) {
		List<MemberBaseinfo> list = getSqlMapClientTemplate().queryForList(
				"MEMBER_BASEINFO.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.MEMBER_BASEINFO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public int updateByExampleSelective(MemberBaseinfo record,
			MemberBaseinfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"MEMBER_BASEINFO.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.MEMBER_BASEINFO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public int updateByExample(MemberBaseinfo record,
			MemberBaseinfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"MEMBER_BASEINFO.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table YLJZN.MEMBER_BASEINFO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private static class UpdateByExampleParms extends MemberBaseinfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, MemberBaseinfoExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}

	@SuppressWarnings("unchecked")
	public List<MemberBaseinfo> selectByExample(MemberBaseinfoExample example,
			int skipResults, int maxResults) {
		List<MemberBaseinfo> list = getSqlMapClientTemplate().queryForList(
				"MEMBER_BASEINFO.ibatorgenerated_selectByExample", example,
				skipResults, maxResults);
		return list;
	}
}