package com.medical.dao;

import com.medical.model.SysTEmployee;
import com.medical.model.SysTEmployeeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SysTEmployeeDAOImpl extends SqlMapClientDaoSupport implements SysTEmployeeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.SYS_T_EMPLOYEE
	 * @ibatorgenerated  Mon Sep 01 13:14:48 CST 2014
	 */
	public SysTEmployeeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.SYS_T_EMPLOYEE
	 * @ibatorgenerated  Mon Sep 01 13:14:48 CST 2014
	 */
	public int countByExample(SysTEmployeeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"SYS_T_EMPLOYEE.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.SYS_T_EMPLOYEE
	 * @ibatorgenerated  Mon Sep 01 13:14:48 CST 2014
	 */
	public int deleteByExample(SysTEmployeeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"SYS_T_EMPLOYEE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.SYS_T_EMPLOYEE
	 * @ibatorgenerated  Mon Sep 01 13:14:48 CST 2014
	 */
	public void insert(SysTEmployee record) {
		getSqlMapClientTemplate().insert(
				"SYS_T_EMPLOYEE.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.SYS_T_EMPLOYEE
	 * @ibatorgenerated  Mon Sep 01 13:14:48 CST 2014
	 */
	public void insertSelective(SysTEmployee record) {
		getSqlMapClientTemplate().insert(
				"SYS_T_EMPLOYEE.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.SYS_T_EMPLOYEE
	 * @ibatorgenerated  Mon Sep 01 13:14:48 CST 2014
	 */
	@SuppressWarnings("unchecked")
	public List<SysTEmployee> selectByExample(SysTEmployeeExample example) {
		List<SysTEmployee> list = getSqlMapClientTemplate().queryForList(
				"SYS_T_EMPLOYEE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.SYS_T_EMPLOYEE
	 * @ibatorgenerated  Mon Sep 01 13:14:48 CST 2014
	 */
	public int updateByExampleSelective(SysTEmployee record,
			SysTEmployeeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"SYS_T_EMPLOYEE.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.SYS_T_EMPLOYEE
	 * @ibatorgenerated  Mon Sep 01 13:14:48 CST 2014
	 */
	public int updateByExample(SysTEmployee record, SysTEmployeeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"SYS_T_EMPLOYEE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table YLJZN.SYS_T_EMPLOYEE
	 * @ibatorgenerated  Mon Sep 01 13:14:48 CST 2014
	 */
	private static class UpdateByExampleParms extends SysTEmployeeExample {
		private Object record;

		public UpdateByExampleParms(Object record, SysTEmployeeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}