package com.medical.dao;

import com.medical.model.TestSsn;
import com.medical.model.TestSsnExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TestSsnDAOImpl extends SqlMapClientDaoSupport implements TestSsnDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.TEST_SSN
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public TestSsnDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.TEST_SSN
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public int countByExample(TestSsnExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TEST_SSN.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.TEST_SSN
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public int deleteByExample(TestSsnExample example) {
        int rows = getSqlMapClientTemplate().delete("TEST_SSN.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.TEST_SSN
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void insert(TestSsn record) {
        getSqlMapClientTemplate().insert("TEST_SSN.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.TEST_SSN
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void insertSelective(TestSsn record) {
        getSqlMapClientTemplate().insert("TEST_SSN.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.TEST_SSN
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<TestSsn> selectByExample(TestSsnExample example) {
        List<TestSsn> list = getSqlMapClientTemplate().queryForList("TEST_SSN.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.TEST_SSN
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public int updateByExampleSelective(TestSsn record, TestSsnExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TEST_SSN.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.TEST_SSN
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public int updateByExample(TestSsn record, TestSsnExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TEST_SSN.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table YLJZN.TEST_SSN
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    private static class UpdateByExampleParms extends TestSsnExample {
        private Object record;

        public UpdateByExampleParms(Object record, TestSsnExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}