package com.medical.dao;

import com.medical.model.VbSearchinfo;
import com.medical.model.VbSearchinfoExample;
import java.util.List;

public interface VbSearchinfoDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	int countByExample(VbSearchinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	int deleteByExample(VbSearchinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	void insert(VbSearchinfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	void insertSelective(VbSearchinfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	List<VbSearchinfo> selectByExample(VbSearchinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	int updateByExampleSelective(VbSearchinfo record,
			VbSearchinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	int updateByExample(VbSearchinfo record, VbSearchinfoExample example);

	public List<VbSearchinfo> selectByExample(VbSearchinfoExample example,int skip,int max);
}