package com.medical.dao;

import com.medical.model.VbSearchinfo;
import com.medical.model.VbSearchinfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VbSearchinfoDAOImpl extends SqlMapClientDaoSupport implements VbSearchinfoDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public VbSearchinfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public int countByExample(VbSearchinfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"VB_SEARCHINFO.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public int deleteByExample(VbSearchinfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"VB_SEARCHINFO.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void insert(VbSearchinfo record) {
		getSqlMapClientTemplate().insert(
				"VB_SEARCHINFO.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void insertSelective(VbSearchinfo record) {
		getSqlMapClientTemplate().insert(
				"VB_SEARCHINFO.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<VbSearchinfo> selectByExample(VbSearchinfoExample example) {
		List<VbSearchinfo> list = getSqlMapClientTemplate().queryForList(
				"VB_SEARCHINFO.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public int updateByExampleSelective(VbSearchinfo record,
			VbSearchinfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"VB_SEARCHINFO.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public int updateByExample(VbSearchinfo record, VbSearchinfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"VB_SEARCHINFO.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table YLJZN.VB_SEARCHINFO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private static class UpdateByExampleParms extends VbSearchinfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, VbSearchinfoExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}

	@SuppressWarnings("unchecked")
    public List<VbSearchinfo> selectByExample(VbSearchinfoExample example,int skip,int max) {
        List<VbSearchinfo> list = getSqlMapClientTemplate().queryForList("VB_SEARCHINFO.ibatorgenerated_selectByExample", example,skip,max);
        return list;
    }
}