package com.medical.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CurrectChronicExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    public CurrectChronicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    protected CurrectChronicExample(CurrectChronicExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table YLJZN.CURRECT_CHRONIC
     *
     * @ibatorgenerated Fri Oct 31 11:26:08 CST 2014
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andEntitysIsNull() {
            addCriterion("ENTITYS is null");
            return this;
        }

        public Criteria andEntitysIsNotNull() {
            addCriterion("ENTITYS is not null");
            return this;
        }

        public Criteria andEntitysEqualTo(String value) {
            addCriterion("ENTITYS =", value, "entitys");
            return this;
        }

        public Criteria andEntitysNotEqualTo(String value) {
            addCriterion("ENTITYS <>", value, "entitys");
            return this;
        }

        public Criteria andEntitysGreaterThan(String value) {
            addCriterion("ENTITYS >", value, "entitys");
            return this;
        }

        public Criteria andEntitysGreaterThanOrEqualTo(String value) {
            addCriterion("ENTITYS >=", value, "entitys");
            return this;
        }

        public Criteria andEntitysLessThan(String value) {
            addCriterion("ENTITYS <", value, "entitys");
            return this;
        }

        public Criteria andEntitysLessThanOrEqualTo(String value) {
            addCriterion("ENTITYS <=", value, "entitys");
            return this;
        }

        public Criteria andEntitysLike(String value) {
            addCriterion("ENTITYS like", value, "entitys");
            return this;
        }

        public Criteria andEntitysNotLike(String value) {
            addCriterion("ENTITYS not like", value, "entitys");
            return this;
        }

        public Criteria andEntitysIn(List<String> values) {
            addCriterion("ENTITYS in", values, "entitys");
            return this;
        }

        public Criteria andEntitysNotIn(List<String> values) {
            addCriterion("ENTITYS not in", values, "entitys");
            return this;
        }

        public Criteria andEntitysBetween(String value1, String value2) {
            addCriterion("ENTITYS between", value1, value2, "entitys");
            return this;
        }

        public Criteria andEntitysNotBetween(String value1, String value2) {
            addCriterion("ENTITYS not between", value1, value2, "entitys");
            return this;
        }

        public Criteria andEntityvalIsNull() {
            addCriterion("ENTITYVAL is null");
            return this;
        }

        public Criteria andEntityvalIsNotNull() {
            addCriterion("ENTITYVAL is not null");
            return this;
        }

        public Criteria andEntityvalEqualTo(String value) {
            addCriterion("ENTITYVAL =", value, "entityval");
            return this;
        }

        public Criteria andEntityvalNotEqualTo(String value) {
            addCriterion("ENTITYVAL <>", value, "entityval");
            return this;
        }

        public Criteria andEntityvalGreaterThan(String value) {
            addCriterion("ENTITYVAL >", value, "entityval");
            return this;
        }

        public Criteria andEntityvalGreaterThanOrEqualTo(String value) {
            addCriterion("ENTITYVAL >=", value, "entityval");
            return this;
        }

        public Criteria andEntityvalLessThan(String value) {
            addCriterion("ENTITYVAL <", value, "entityval");
            return this;
        }

        public Criteria andEntityvalLessThanOrEqualTo(String value) {
            addCriterion("ENTITYVAL <=", value, "entityval");
            return this;
        }

        public Criteria andEntityvalLike(String value) {
            addCriterion("ENTITYVAL like", value, "entityval");
            return this;
        }

        public Criteria andEntityvalNotLike(String value) {
            addCriterion("ENTITYVAL not like", value, "entityval");
            return this;
        }

        public Criteria andEntityvalIn(List<String> values) {
            addCriterion("ENTITYVAL in", values, "entityval");
            return this;
        }

        public Criteria andEntityvalNotIn(List<String> values) {
            addCriterion("ENTITYVAL not in", values, "entityval");
            return this;
        }

        public Criteria andEntityvalBetween(String value1, String value2) {
            addCriterion("ENTITYVAL between", value1, value2, "entityval");
            return this;
        }

        public Criteria andEntityvalNotBetween(String value1, String value2) {
            addCriterion("ENTITYVAL not between", value1, value2, "entityval");
            return this;
        }

        public Criteria andAprresult1IsNull() {
            addCriterion("APRRESULT1 is null");
            return this;
        }

        public Criteria andAprresult1IsNotNull() {
            addCriterion("APRRESULT1 is not null");
            return this;
        }

        public Criteria andAprresult1EqualTo(Short value) {
            addCriterion("APRRESULT1 =", value, "aprresult1");
            return this;
        }

        public Criteria andAprresult1NotEqualTo(Short value) {
            addCriterion("APRRESULT1 <>", value, "aprresult1");
            return this;
        }

        public Criteria andAprresult1GreaterThan(Short value) {
            addCriterion("APRRESULT1 >", value, "aprresult1");
            return this;
        }

        public Criteria andAprresult1GreaterThanOrEqualTo(Short value) {
            addCriterion("APRRESULT1 >=", value, "aprresult1");
            return this;
        }

        public Criteria andAprresult1LessThan(Short value) {
            addCriterion("APRRESULT1 <", value, "aprresult1");
            return this;
        }

        public Criteria andAprresult1LessThanOrEqualTo(Short value) {
            addCriterion("APRRESULT1 <=", value, "aprresult1");
            return this;
        }

        public Criteria andAprresult1In(List<Short> values) {
            addCriterion("APRRESULT1 in", values, "aprresult1");
            return this;
        }

        public Criteria andAprresult1NotIn(List<Short> values) {
            addCriterion("APRRESULT1 not in", values, "aprresult1");
            return this;
        }

        public Criteria andAprresult1Between(Short value1, Short value2) {
            addCriterion("APRRESULT1 between", value1, value2, "aprresult1");
            return this;
        }

        public Criteria andAprresult1NotBetween(Short value1, Short value2) {
            addCriterion("APRRESULT1 not between", value1, value2, "aprresult1");
            return this;
        }

        public Criteria andApridea1IsNull() {
            addCriterion("APRIDEA1 is null");
            return this;
        }

        public Criteria andApridea1IsNotNull() {
            addCriterion("APRIDEA1 is not null");
            return this;
        }

        public Criteria andApridea1EqualTo(String value) {
            addCriterion("APRIDEA1 =", value, "apridea1");
            return this;
        }

        public Criteria andApridea1NotEqualTo(String value) {
            addCriterion("APRIDEA1 <>", value, "apridea1");
            return this;
        }

        public Criteria andApridea1GreaterThan(String value) {
            addCriterion("APRIDEA1 >", value, "apridea1");
            return this;
        }

        public Criteria andApridea1GreaterThanOrEqualTo(String value) {
            addCriterion("APRIDEA1 >=", value, "apridea1");
            return this;
        }

        public Criteria andApridea1LessThan(String value) {
            addCriterion("APRIDEA1 <", value, "apridea1");
            return this;
        }

        public Criteria andApridea1LessThanOrEqualTo(String value) {
            addCriterion("APRIDEA1 <=", value, "apridea1");
            return this;
        }

        public Criteria andApridea1Like(String value) {
            addCriterion("APRIDEA1 like", value, "apridea1");
            return this;
        }

        public Criteria andApridea1NotLike(String value) {
            addCriterion("APRIDEA1 not like", value, "apridea1");
            return this;
        }

        public Criteria andApridea1In(List<String> values) {
            addCriterion("APRIDEA1 in", values, "apridea1");
            return this;
        }

        public Criteria andApridea1NotIn(List<String> values) {
            addCriterion("APRIDEA1 not in", values, "apridea1");
            return this;
        }

        public Criteria andApridea1Between(String value1, String value2) {
            addCriterion("APRIDEA1 between", value1, value2, "apridea1");
            return this;
        }

        public Criteria andApridea1NotBetween(String value1, String value2) {
            addCriterion("APRIDEA1 not between", value1, value2, "apridea1");
            return this;
        }

        public Criteria andAprtime1IsNull() {
            addCriterion("APRTIME1 is null");
            return this;
        }

        public Criteria andAprtime1IsNotNull() {
            addCriterion("APRTIME1 is not null");
            return this;
        }

        public Criteria andAprtime1EqualTo(Date value) {
            addCriterion("APRTIME1 =", value, "aprtime1");
            return this;
        }

        public Criteria andAprtime1NotEqualTo(Date value) {
            addCriterion("APRTIME1 <>", value, "aprtime1");
            return this;
        }

        public Criteria andAprtime1GreaterThan(Date value) {
            addCriterion("APRTIME1 >", value, "aprtime1");
            return this;
        }

        public Criteria andAprtime1GreaterThanOrEqualTo(Date value) {
            addCriterion("APRTIME1 >=", value, "aprtime1");
            return this;
        }

        public Criteria andAprtime1LessThan(Date value) {
            addCriterion("APRTIME1 <", value, "aprtime1");
            return this;
        }

        public Criteria andAprtime1LessThanOrEqualTo(Date value) {
            addCriterion("APRTIME1 <=", value, "aprtime1");
            return this;
        }

        public Criteria andAprtime1In(List<Date> values) {
            addCriterion("APRTIME1 in", values, "aprtime1");
            return this;
        }

        public Criteria andAprtime1NotIn(List<Date> values) {
            addCriterion("APRTIME1 not in", values, "aprtime1");
            return this;
        }

        public Criteria andAprtime1Between(Date value1, Date value2) {
            addCriterion("APRTIME1 between", value1, value2, "aprtime1");
            return this;
        }

        public Criteria andAprtime1NotBetween(Date value1, Date value2) {
            addCriterion("APRTIME1 not between", value1, value2, "aprtime1");
            return this;
        }

        public Criteria andAprperson1IsNull() {
            addCriterion("APRPERSON1 is null");
            return this;
        }

        public Criteria andAprperson1IsNotNull() {
            addCriterion("APRPERSON1 is not null");
            return this;
        }

        public Criteria andAprperson1EqualTo(String value) {
            addCriterion("APRPERSON1 =", value, "aprperson1");
            return this;
        }

        public Criteria andAprperson1NotEqualTo(String value) {
            addCriterion("APRPERSON1 <>", value, "aprperson1");
            return this;
        }

        public Criteria andAprperson1GreaterThan(String value) {
            addCriterion("APRPERSON1 >", value, "aprperson1");
            return this;
        }

        public Criteria andAprperson1GreaterThanOrEqualTo(String value) {
            addCriterion("APRPERSON1 >=", value, "aprperson1");
            return this;
        }

        public Criteria andAprperson1LessThan(String value) {
            addCriterion("APRPERSON1 <", value, "aprperson1");
            return this;
        }

        public Criteria andAprperson1LessThanOrEqualTo(String value) {
            addCriterion("APRPERSON1 <=", value, "aprperson1");
            return this;
        }

        public Criteria andAprperson1Like(String value) {
            addCriterion("APRPERSON1 like", value, "aprperson1");
            return this;
        }

        public Criteria andAprperson1NotLike(String value) {
            addCriterion("APRPERSON1 not like", value, "aprperson1");
            return this;
        }

        public Criteria andAprperson1In(List<String> values) {
            addCriterion("APRPERSON1 in", values, "aprperson1");
            return this;
        }

        public Criteria andAprperson1NotIn(List<String> values) {
            addCriterion("APRPERSON1 not in", values, "aprperson1");
            return this;
        }

        public Criteria andAprperson1Between(String value1, String value2) {
            addCriterion("APRPERSON1 between", value1, value2, "aprperson1");
            return this;
        }

        public Criteria andAprperson1NotBetween(String value1, String value2) {
            addCriterion("APRPERSON1 not between", value1, value2, "aprperson1");
            return this;
        }

        public Criteria andAprresult2IsNull() {
            addCriterion("APRRESULT2 is null");
            return this;
        }

        public Criteria andAprresult2IsNotNull() {
            addCriterion("APRRESULT2 is not null");
            return this;
        }

        public Criteria andAprresult2EqualTo(Short value) {
            addCriterion("APRRESULT2 =", value, "aprresult2");
            return this;
        }

        public Criteria andAprresult2NotEqualTo(Short value) {
            addCriterion("APRRESULT2 <>", value, "aprresult2");
            return this;
        }

        public Criteria andAprresult2GreaterThan(Short value) {
            addCriterion("APRRESULT2 >", value, "aprresult2");
            return this;
        }

        public Criteria andAprresult2GreaterThanOrEqualTo(Short value) {
            addCriterion("APRRESULT2 >=", value, "aprresult2");
            return this;
        }

        public Criteria andAprresult2LessThan(Short value) {
            addCriterion("APRRESULT2 <", value, "aprresult2");
            return this;
        }

        public Criteria andAprresult2LessThanOrEqualTo(Short value) {
            addCriterion("APRRESULT2 <=", value, "aprresult2");
            return this;
        }

        public Criteria andAprresult2In(List<Short> values) {
            addCriterion("APRRESULT2 in", values, "aprresult2");
            return this;
        }

        public Criteria andAprresult2NotIn(List<Short> values) {
            addCriterion("APRRESULT2 not in", values, "aprresult2");
            return this;
        }

        public Criteria andAprresult2Between(Short value1, Short value2) {
            addCriterion("APRRESULT2 between", value1, value2, "aprresult2");
            return this;
        }

        public Criteria andAprresult2NotBetween(Short value1, Short value2) {
            addCriterion("APRRESULT2 not between", value1, value2, "aprresult2");
            return this;
        }

        public Criteria andApridea2IsNull() {
            addCriterion("APRIDEA2 is null");
            return this;
        }

        public Criteria andApridea2IsNotNull() {
            addCriterion("APRIDEA2 is not null");
            return this;
        }

        public Criteria andApridea2EqualTo(String value) {
            addCriterion("APRIDEA2 =", value, "apridea2");
            return this;
        }

        public Criteria andApridea2NotEqualTo(String value) {
            addCriterion("APRIDEA2 <>", value, "apridea2");
            return this;
        }

        public Criteria andApridea2GreaterThan(String value) {
            addCriterion("APRIDEA2 >", value, "apridea2");
            return this;
        }

        public Criteria andApridea2GreaterThanOrEqualTo(String value) {
            addCriterion("APRIDEA2 >=", value, "apridea2");
            return this;
        }

        public Criteria andApridea2LessThan(String value) {
            addCriterion("APRIDEA2 <", value, "apridea2");
            return this;
        }

        public Criteria andApridea2LessThanOrEqualTo(String value) {
            addCriterion("APRIDEA2 <=", value, "apridea2");
            return this;
        }

        public Criteria andApridea2Like(String value) {
            addCriterion("APRIDEA2 like", value, "apridea2");
            return this;
        }

        public Criteria andApridea2NotLike(String value) {
            addCriterion("APRIDEA2 not like", value, "apridea2");
            return this;
        }

        public Criteria andApridea2In(List<String> values) {
            addCriterion("APRIDEA2 in", values, "apridea2");
            return this;
        }

        public Criteria andApridea2NotIn(List<String> values) {
            addCriterion("APRIDEA2 not in", values, "apridea2");
            return this;
        }

        public Criteria andApridea2Between(String value1, String value2) {
            addCriterion("APRIDEA2 between", value1, value2, "apridea2");
            return this;
        }

        public Criteria andApridea2NotBetween(String value1, String value2) {
            addCriterion("APRIDEA2 not between", value1, value2, "apridea2");
            return this;
        }

        public Criteria andAprtime2IsNull() {
            addCriterion("APRTIME2 is null");
            return this;
        }

        public Criteria andAprtime2IsNotNull() {
            addCriterion("APRTIME2 is not null");
            return this;
        }

        public Criteria andAprtime2EqualTo(Date value) {
            addCriterion("APRTIME2 =", value, "aprtime2");
            return this;
        }

        public Criteria andAprtime2NotEqualTo(Date value) {
            addCriterion("APRTIME2 <>", value, "aprtime2");
            return this;
        }

        public Criteria andAprtime2GreaterThan(Date value) {
            addCriterion("APRTIME2 >", value, "aprtime2");
            return this;
        }

        public Criteria andAprtime2GreaterThanOrEqualTo(Date value) {
            addCriterion("APRTIME2 >=", value, "aprtime2");
            return this;
        }

        public Criteria andAprtime2LessThan(Date value) {
            addCriterion("APRTIME2 <", value, "aprtime2");
            return this;
        }

        public Criteria andAprtime2LessThanOrEqualTo(Date value) {
            addCriterion("APRTIME2 <=", value, "aprtime2");
            return this;
        }

        public Criteria andAprtime2In(List<Date> values) {
            addCriterion("APRTIME2 in", values, "aprtime2");
            return this;
        }

        public Criteria andAprtime2NotIn(List<Date> values) {
            addCriterion("APRTIME2 not in", values, "aprtime2");
            return this;
        }

        public Criteria andAprtime2Between(Date value1, Date value2) {
            addCriterion("APRTIME2 between", value1, value2, "aprtime2");
            return this;
        }

        public Criteria andAprtime2NotBetween(Date value1, Date value2) {
            addCriterion("APRTIME2 not between", value1, value2, "aprtime2");
            return this;
        }

        public Criteria andAprperson2IsNull() {
            addCriterion("APRPERSON2 is null");
            return this;
        }

        public Criteria andAprperson2IsNotNull() {
            addCriterion("APRPERSON2 is not null");
            return this;
        }

        public Criteria andAprperson2EqualTo(String value) {
            addCriterion("APRPERSON2 =", value, "aprperson2");
            return this;
        }

        public Criteria andAprperson2NotEqualTo(String value) {
            addCriterion("APRPERSON2 <>", value, "aprperson2");
            return this;
        }

        public Criteria andAprperson2GreaterThan(String value) {
            addCriterion("APRPERSON2 >", value, "aprperson2");
            return this;
        }

        public Criteria andAprperson2GreaterThanOrEqualTo(String value) {
            addCriterion("APRPERSON2 >=", value, "aprperson2");
            return this;
        }

        public Criteria andAprperson2LessThan(String value) {
            addCriterion("APRPERSON2 <", value, "aprperson2");
            return this;
        }

        public Criteria andAprperson2LessThanOrEqualTo(String value) {
            addCriterion("APRPERSON2 <=", value, "aprperson2");
            return this;
        }

        public Criteria andAprperson2Like(String value) {
            addCriterion("APRPERSON2 like", value, "aprperson2");
            return this;
        }

        public Criteria andAprperson2NotLike(String value) {
            addCriterion("APRPERSON2 not like", value, "aprperson2");
            return this;
        }

        public Criteria andAprperson2In(List<String> values) {
            addCriterion("APRPERSON2 in", values, "aprperson2");
            return this;
        }

        public Criteria andAprperson2NotIn(List<String> values) {
            addCriterion("APRPERSON2 not in", values, "aprperson2");
            return this;
        }

        public Criteria andAprperson2Between(String value1, String value2) {
            addCriterion("APRPERSON2 between", value1, value2, "aprperson2");
            return this;
        }

        public Criteria andAprperson2NotBetween(String value1, String value2) {
            addCriterion("APRPERSON2 not between", value1, value2, "aprperson2");
            return this;
        }

        public Criteria andAprresult3IsNull() {
            addCriterion("APRRESULT3 is null");
            return this;
        }

        public Criteria andAprresult3IsNotNull() {
            addCriterion("APRRESULT3 is not null");
            return this;
        }

        public Criteria andAprresult3EqualTo(Short value) {
            addCriterion("APRRESULT3 =", value, "aprresult3");
            return this;
        }

        public Criteria andAprresult3NotEqualTo(Short value) {
            addCriterion("APRRESULT3 <>", value, "aprresult3");
            return this;
        }

        public Criteria andAprresult3GreaterThan(Short value) {
            addCriterion("APRRESULT3 >", value, "aprresult3");
            return this;
        }

        public Criteria andAprresult3GreaterThanOrEqualTo(Short value) {
            addCriterion("APRRESULT3 >=", value, "aprresult3");
            return this;
        }

        public Criteria andAprresult3LessThan(Short value) {
            addCriterion("APRRESULT3 <", value, "aprresult3");
            return this;
        }

        public Criteria andAprresult3LessThanOrEqualTo(Short value) {
            addCriterion("APRRESULT3 <=", value, "aprresult3");
            return this;
        }

        public Criteria andAprresult3In(List<Short> values) {
            addCriterion("APRRESULT3 in", values, "aprresult3");
            return this;
        }

        public Criteria andAprresult3NotIn(List<Short> values) {
            addCriterion("APRRESULT3 not in", values, "aprresult3");
            return this;
        }

        public Criteria andAprresult3Between(Short value1, Short value2) {
            addCriterion("APRRESULT3 between", value1, value2, "aprresult3");
            return this;
        }

        public Criteria andAprresult3NotBetween(Short value1, Short value2) {
            addCriterion("APRRESULT3 not between", value1, value2, "aprresult3");
            return this;
        }

        public Criteria andApridea3IsNull() {
            addCriterion("APRIDEA3 is null");
            return this;
        }

        public Criteria andApridea3IsNotNull() {
            addCriterion("APRIDEA3 is not null");
            return this;
        }

        public Criteria andApridea3EqualTo(String value) {
            addCriterion("APRIDEA3 =", value, "apridea3");
            return this;
        }

        public Criteria andApridea3NotEqualTo(String value) {
            addCriterion("APRIDEA3 <>", value, "apridea3");
            return this;
        }

        public Criteria andApridea3GreaterThan(String value) {
            addCriterion("APRIDEA3 >", value, "apridea3");
            return this;
        }

        public Criteria andApridea3GreaterThanOrEqualTo(String value) {
            addCriterion("APRIDEA3 >=", value, "apridea3");
            return this;
        }

        public Criteria andApridea3LessThan(String value) {
            addCriterion("APRIDEA3 <", value, "apridea3");
            return this;
        }

        public Criteria andApridea3LessThanOrEqualTo(String value) {
            addCriterion("APRIDEA3 <=", value, "apridea3");
            return this;
        }

        public Criteria andApridea3Like(String value) {
            addCriterion("APRIDEA3 like", value, "apridea3");
            return this;
        }

        public Criteria andApridea3NotLike(String value) {
            addCriterion("APRIDEA3 not like", value, "apridea3");
            return this;
        }

        public Criteria andApridea3In(List<String> values) {
            addCriterion("APRIDEA3 in", values, "apridea3");
            return this;
        }

        public Criteria andApridea3NotIn(List<String> values) {
            addCriterion("APRIDEA3 not in", values, "apridea3");
            return this;
        }

        public Criteria andApridea3Between(String value1, String value2) {
            addCriterion("APRIDEA3 between", value1, value2, "apridea3");
            return this;
        }

        public Criteria andApridea3NotBetween(String value1, String value2) {
            addCriterion("APRIDEA3 not between", value1, value2, "apridea3");
            return this;
        }

        public Criteria andAprtime3IsNull() {
            addCriterion("APRTIME3 is null");
            return this;
        }

        public Criteria andAprtime3IsNotNull() {
            addCriterion("APRTIME3 is not null");
            return this;
        }

        public Criteria andAprtime3EqualTo(Date value) {
            addCriterion("APRTIME3 =", value, "aprtime3");
            return this;
        }

        public Criteria andAprtime3NotEqualTo(Date value) {
            addCriterion("APRTIME3 <>", value, "aprtime3");
            return this;
        }

        public Criteria andAprtime3GreaterThan(Date value) {
            addCriterion("APRTIME3 >", value, "aprtime3");
            return this;
        }

        public Criteria andAprtime3GreaterThanOrEqualTo(Date value) {
            addCriterion("APRTIME3 >=", value, "aprtime3");
            return this;
        }

        public Criteria andAprtime3LessThan(Date value) {
            addCriterion("APRTIME3 <", value, "aprtime3");
            return this;
        }

        public Criteria andAprtime3LessThanOrEqualTo(Date value) {
            addCriterion("APRTIME3 <=", value, "aprtime3");
            return this;
        }

        public Criteria andAprtime3In(List<Date> values) {
            addCriterion("APRTIME3 in", values, "aprtime3");
            return this;
        }

        public Criteria andAprtime3NotIn(List<Date> values) {
            addCriterion("APRTIME3 not in", values, "aprtime3");
            return this;
        }

        public Criteria andAprtime3Between(Date value1, Date value2) {
            addCriterion("APRTIME3 between", value1, value2, "aprtime3");
            return this;
        }

        public Criteria andAprtime3NotBetween(Date value1, Date value2) {
            addCriterion("APRTIME3 not between", value1, value2, "aprtime3");
            return this;
        }

        public Criteria andAprperson3IsNull() {
            addCriterion("APRPERSON3 is null");
            return this;
        }

        public Criteria andAprperson3IsNotNull() {
            addCriterion("APRPERSON3 is not null");
            return this;
        }

        public Criteria andAprperson3EqualTo(String value) {
            addCriterion("APRPERSON3 =", value, "aprperson3");
            return this;
        }

        public Criteria andAprperson3NotEqualTo(String value) {
            addCriterion("APRPERSON3 <>", value, "aprperson3");
            return this;
        }

        public Criteria andAprperson3GreaterThan(String value) {
            addCriterion("APRPERSON3 >", value, "aprperson3");
            return this;
        }

        public Criteria andAprperson3GreaterThanOrEqualTo(String value) {
            addCriterion("APRPERSON3 >=", value, "aprperson3");
            return this;
        }

        public Criteria andAprperson3LessThan(String value) {
            addCriterion("APRPERSON3 <", value, "aprperson3");
            return this;
        }

        public Criteria andAprperson3LessThanOrEqualTo(String value) {
            addCriterion("APRPERSON3 <=", value, "aprperson3");
            return this;
        }

        public Criteria andAprperson3Like(String value) {
            addCriterion("APRPERSON3 like", value, "aprperson3");
            return this;
        }

        public Criteria andAprperson3NotLike(String value) {
            addCriterion("APRPERSON3 not like", value, "aprperson3");
            return this;
        }

        public Criteria andAprperson3In(List<String> values) {
            addCriterion("APRPERSON3 in", values, "aprperson3");
            return this;
        }

        public Criteria andAprperson3NotIn(List<String> values) {
            addCriterion("APRPERSON3 not in", values, "aprperson3");
            return this;
        }

        public Criteria andAprperson3Between(String value1, String value2) {
            addCriterion("APRPERSON3 between", value1, value2, "aprperson3");
            return this;
        }

        public Criteria andAprperson3NotBetween(String value1, String value2) {
            addCriterion("APRPERSON3 not between", value1, value2, "aprperson3");
            return this;
        }

        public Criteria andAprlevelIsNull() {
            addCriterion("APRLEVEL is null");
            return this;
        }

        public Criteria andAprlevelIsNotNull() {
            addCriterion("APRLEVEL is not null");
            return this;
        }

        public Criteria andAprlevelEqualTo(Short value) {
            addCriterion("APRLEVEL =", value, "aprlevel");
            return this;
        }

        public Criteria andAprlevelNotEqualTo(Short value) {
            addCriterion("APRLEVEL <>", value, "aprlevel");
            return this;
        }

        public Criteria andAprlevelGreaterThan(Short value) {
            addCriterion("APRLEVEL >", value, "aprlevel");
            return this;
        }

        public Criteria andAprlevelGreaterThanOrEqualTo(Short value) {
            addCriterion("APRLEVEL >=", value, "aprlevel");
            return this;
        }

        public Criteria andAprlevelLessThan(Short value) {
            addCriterion("APRLEVEL <", value, "aprlevel");
            return this;
        }

        public Criteria andAprlevelLessThanOrEqualTo(Short value) {
            addCriterion("APRLEVEL <=", value, "aprlevel");
            return this;
        }

        public Criteria andAprlevelIn(List<Short> values) {
            addCriterion("APRLEVEL in", values, "aprlevel");
            return this;
        }

        public Criteria andAprlevelNotIn(List<Short> values) {
            addCriterion("APRLEVEL not in", values, "aprlevel");
            return this;
        }

        public Criteria andAprlevelBetween(Short value1, Short value2) {
            addCriterion("APRLEVEL between", value1, value2, "aprlevel");
            return this;
        }

        public Criteria andAprlevelNotBetween(Short value1, Short value2) {
            addCriterion("APRLEVEL not between", value1, value2, "aprlevel");
            return this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("FLAG is null");
            return this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("FLAG is not null");
            return this;
        }

        public Criteria andFlagEqualTo(Short value) {
            addCriterion("FLAG =", value, "flag");
            return this;
        }

        public Criteria andFlagNotEqualTo(Short value) {
            addCriterion("FLAG <>", value, "flag");
            return this;
        }

        public Criteria andFlagGreaterThan(Short value) {
            addCriterion("FLAG >", value, "flag");
            return this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("FLAG >=", value, "flag");
            return this;
        }

        public Criteria andFlagLessThan(Short value) {
            addCriterion("FLAG <", value, "flag");
            return this;
        }

        public Criteria andFlagLessThanOrEqualTo(Short value) {
            addCriterion("FLAG <=", value, "flag");
            return this;
        }

        public Criteria andFlagIn(List<Short> values) {
            addCriterion("FLAG in", values, "flag");
            return this;
        }

        public Criteria andFlagNotIn(List<Short> values) {
            addCriterion("FLAG not in", values, "flag");
            return this;
        }

        public Criteria andFlagBetween(Short value1, Short value2) {
            addCriterion("FLAG between", value1, value2, "flag");
            return this;
        }

        public Criteria andFlagNotBetween(Short value1, Short value2) {
            addCriterion("FLAG not between", value1, value2, "flag");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andChronicstatusId1IsNull() {
            addCriterion("CHRONICSTATUS_ID1 is null");
            return this;
        }

        public Criteria andChronicstatusId1IsNotNull() {
            addCriterion("CHRONICSTATUS_ID1 is not null");
            return this;
        }

        public Criteria andChronicstatusId1EqualTo(Long value) {
            addCriterion("CHRONICSTATUS_ID1 =", value, "chronicstatusId1");
            return this;
        }

        public Criteria andChronicstatusId1NotEqualTo(Long value) {
            addCriterion("CHRONICSTATUS_ID1 <>", value, "chronicstatusId1");
            return this;
        }

        public Criteria andChronicstatusId1GreaterThan(Long value) {
            addCriterion("CHRONICSTATUS_ID1 >", value, "chronicstatusId1");
            return this;
        }

        public Criteria andChronicstatusId1GreaterThanOrEqualTo(Long value) {
            addCriterion("CHRONICSTATUS_ID1 >=", value, "chronicstatusId1");
            return this;
        }

        public Criteria andChronicstatusId1LessThan(Long value) {
            addCriterion("CHRONICSTATUS_ID1 <", value, "chronicstatusId1");
            return this;
        }

        public Criteria andChronicstatusId1LessThanOrEqualTo(Long value) {
            addCriterion("CHRONICSTATUS_ID1 <=", value, "chronicstatusId1");
            return this;
        }

        public Criteria andChronicstatusId1In(List<Long> values) {
            addCriterion("CHRONICSTATUS_ID1 in", values, "chronicstatusId1");
            return this;
        }

        public Criteria andChronicstatusId1NotIn(List<Long> values) {
            addCriterion("CHRONICSTATUS_ID1 not in", values, "chronicstatusId1");
            return this;
        }

        public Criteria andChronicstatusId1Between(Long value1, Long value2) {
            addCriterion("CHRONICSTATUS_ID1 between", value1, value2, "chronicstatusId1");
            return this;
        }

        public Criteria andChronicstatusId1NotBetween(Long value1, Long value2) {
            addCriterion("CHRONICSTATUS_ID1 not between", value1, value2, "chronicstatusId1");
            return this;
        }

        public Criteria andFamilyIdIsNull() {
            addCriterion("FAMILY_ID is null");
            return this;
        }

        public Criteria andFamilyIdIsNotNull() {
            addCriterion("FAMILY_ID is not null");
            return this;
        }

        public Criteria andFamilyIdEqualTo(String value) {
            addCriterion("FAMILY_ID =", value, "familyId");
            return this;
        }

        public Criteria andFamilyIdNotEqualTo(String value) {
            addCriterion("FAMILY_ID <>", value, "familyId");
            return this;
        }

        public Criteria andFamilyIdGreaterThan(String value) {
            addCriterion("FAMILY_ID >", value, "familyId");
            return this;
        }

        public Criteria andFamilyIdGreaterThanOrEqualTo(String value) {
            addCriterion("FAMILY_ID >=", value, "familyId");
            return this;
        }

        public Criteria andFamilyIdLessThan(String value) {
            addCriterion("FAMILY_ID <", value, "familyId");
            return this;
        }

        public Criteria andFamilyIdLessThanOrEqualTo(String value) {
            addCriterion("FAMILY_ID <=", value, "familyId");
            return this;
        }

        public Criteria andFamilyIdLike(String value) {
            addCriterion("FAMILY_ID like", value, "familyId");
            return this;
        }

        public Criteria andFamilyIdNotLike(String value) {
            addCriterion("FAMILY_ID not like", value, "familyId");
            return this;
        }

        public Criteria andFamilyIdIn(List<String> values) {
            addCriterion("FAMILY_ID in", values, "familyId");
            return this;
        }

        public Criteria andFamilyIdNotIn(List<String> values) {
            addCriterion("FAMILY_ID not in", values, "familyId");
            return this;
        }

        public Criteria andFamilyIdBetween(String value1, String value2) {
            addCriterion("FAMILY_ID between", value1, value2, "familyId");
            return this;
        }

        public Criteria andFamilyIdNotBetween(String value1, String value2) {
            addCriterion("FAMILY_ID not between", value1, value2, "familyId");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andSsnIsNull() {
            addCriterion("SSN is null");
            return this;
        }

        public Criteria andSsnIsNotNull() {
            addCriterion("SSN is not null");
            return this;
        }

        public Criteria andSsnEqualTo(String value) {
            addCriterion("SSN =", value, "ssn");
            return this;
        }

        public Criteria andSsnNotEqualTo(String value) {
            addCriterion("SSN <>", value, "ssn");
            return this;
        }

        public Criteria andSsnGreaterThan(String value) {
            addCriterion("SSN >", value, "ssn");
            return this;
        }

        public Criteria andSsnGreaterThanOrEqualTo(String value) {
            addCriterion("SSN >=", value, "ssn");
            return this;
        }

        public Criteria andSsnLessThan(String value) {
            addCriterion("SSN <", value, "ssn");
            return this;
        }

        public Criteria andSsnLessThanOrEqualTo(String value) {
            addCriterion("SSN <=", value, "ssn");
            return this;
        }

        public Criteria andSsnLike(String value) {
            addCriterion("SSN like", value, "ssn");
            return this;
        }

        public Criteria andSsnNotLike(String value) {
            addCriterion("SSN not like", value, "ssn");
            return this;
        }

        public Criteria andSsnIn(List<String> values) {
            addCriterion("SSN in", values, "ssn");
            return this;
        }

        public Criteria andSsnNotIn(List<String> values) {
            addCriterion("SSN not in", values, "ssn");
            return this;
        }

        public Criteria andSsnBetween(String value1, String value2) {
            addCriterion("SSN between", value1, value2, "ssn");
            return this;
        }

        public Criteria andSsnNotBetween(String value1, String value2) {
            addCriterion("SSN not between", value1, value2, "ssn");
            return this;
        }

        public Criteria andEntityIsNull() {
            addCriterion("ENTITY is null");
            return this;
        }

        public Criteria andEntityIsNotNull() {
            addCriterion("ENTITY is not null");
            return this;
        }

        public Criteria andEntityEqualTo(Integer value) {
            addCriterion("ENTITY =", value, "entity");
            return this;
        }

        public Criteria andEntityNotEqualTo(Integer value) {
            addCriterion("ENTITY <>", value, "entity");
            return this;
        }

        public Criteria andEntityGreaterThan(Integer value) {
            addCriterion("ENTITY >", value, "entity");
            return this;
        }

        public Criteria andEntityGreaterThanOrEqualTo(Integer value) {
            addCriterion("ENTITY >=", value, "entity");
            return this;
        }

        public Criteria andEntityLessThan(Integer value) {
            addCriterion("ENTITY <", value, "entity");
            return this;
        }

        public Criteria andEntityLessThanOrEqualTo(Integer value) {
            addCriterion("ENTITY <=", value, "entity");
            return this;
        }

        public Criteria andEntityIn(List<Integer> values) {
            addCriterion("ENTITY in", values, "entity");
            return this;
        }

        public Criteria andEntityNotIn(List<Integer> values) {
            addCriterion("ENTITY not in", values, "entity");
            return this;
        }

        public Criteria andEntityBetween(Integer value1, Integer value2) {
            addCriterion("ENTITY between", value1, value2, "entity");
            return this;
        }

        public Criteria andEntityNotBetween(Integer value1, Integer value2) {
            addCriterion("ENTITY not between", value1, value2, "entity");
            return this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return this;
        }

        public Criteria andApptimeIsNull() {
            addCriterion("APPTIME is null");
            return this;
        }

        public Criteria andApptimeIsNotNull() {
            addCriterion("APPTIME is not null");
            return this;
        }

        public Criteria andApptimeEqualTo(Date value) {
            addCriterion("APPTIME =", value, "apptime");
            return this;
        }

        public Criteria andApptimeNotEqualTo(Date value) {
            addCriterion("APPTIME <>", value, "apptime");
            return this;
        }

        public Criteria andApptimeGreaterThan(Date value) {
            addCriterion("APPTIME >", value, "apptime");
            return this;
        }

        public Criteria andApptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("APPTIME >=", value, "apptime");
            return this;
        }

        public Criteria andApptimeLessThan(Date value) {
            addCriterion("APPTIME <", value, "apptime");
            return this;
        }

        public Criteria andApptimeLessThanOrEqualTo(Date value) {
            addCriterion("APPTIME <=", value, "apptime");
            return this;
        }

        public Criteria andApptimeIn(List<Date> values) {
            addCriterion("APPTIME in", values, "apptime");
            return this;
        }

        public Criteria andApptimeNotIn(List<Date> values) {
            addCriterion("APPTIME not in", values, "apptime");
            return this;
        }

        public Criteria andApptimeBetween(Date value1, Date value2) {
            addCriterion("APPTIME between", value1, value2, "apptime");
            return this;
        }

        public Criteria andApptimeNotBetween(Date value1, Date value2) {
            addCriterion("APPTIME not between", value1, value2, "apptime");
            return this;
        }

        public Criteria andFlag1IsNull() {
            addCriterion("FLAG1 is null");
            return this;
        }

        public Criteria andFlag1IsNotNull() {
            addCriterion("FLAG1 is not null");
            return this;
        }

        public Criteria andFlag1EqualTo(String value) {
            addCriterion("FLAG1 =", value, "flag1");
            return this;
        }

        public Criteria andFlag1NotEqualTo(String value) {
            addCriterion("FLAG1 <>", value, "flag1");
            return this;
        }

        public Criteria andFlag1GreaterThan(String value) {
            addCriterion("FLAG1 >", value, "flag1");
            return this;
        }

        public Criteria andFlag1GreaterThanOrEqualTo(String value) {
            addCriterion("FLAG1 >=", value, "flag1");
            return this;
        }

        public Criteria andFlag1LessThan(String value) {
            addCriterion("FLAG1 <", value, "flag1");
            return this;
        }

        public Criteria andFlag1LessThanOrEqualTo(String value) {
            addCriterion("FLAG1 <=", value, "flag1");
            return this;
        }

        public Criteria andFlag1Like(String value) {
            addCriterion("FLAG1 like", value, "flag1");
            return this;
        }

        public Criteria andFlag1NotLike(String value) {
            addCriterion("FLAG1 not like", value, "flag1");
            return this;
        }

        public Criteria andFlag1In(List<String> values) {
            addCriterion("FLAG1 in", values, "flag1");
            return this;
        }

        public Criteria andFlag1NotIn(List<String> values) {
            addCriterion("FLAG1 not in", values, "flag1");
            return this;
        }

        public Criteria andFlag1Between(String value1, String value2) {
            addCriterion("FLAG1 between", value1, value2, "flag1");
            return this;
        }

        public Criteria andFlag1NotBetween(String value1, String value2) {
            addCriterion("FLAG1 not between", value1, value2, "flag1");
            return this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("MEMBER_ID is null");
            return this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("MEMBER_ID is not null");
            return this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("MEMBER_ID =", value, "memberId");
            return this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("MEMBER_ID <>", value, "memberId");
            return this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("MEMBER_ID >", value, "memberId");
            return this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_ID >=", value, "memberId");
            return this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("MEMBER_ID <", value, "memberId");
            return this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_ID <=", value, "memberId");
            return this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("MEMBER_ID like", value, "memberId");
            return this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("MEMBER_ID not like", value, "memberId");
            return this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("MEMBER_ID in", values, "memberId");
            return this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("MEMBER_ID not in", values, "memberId");
            return this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("MEMBER_ID between", value1, value2, "memberId");
            return this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("MEMBER_ID not between", value1, value2, "memberId");
            return this;
        }

        public Criteria andMemberTypeIsNull() {
            addCriterion("MEMBER_TYPE is null");
            return this;
        }

        public Criteria andMemberTypeIsNotNull() {
            addCriterion("MEMBER_TYPE is not null");
            return this;
        }

        public Criteria andMemberTypeEqualTo(String value) {
            addCriterion("MEMBER_TYPE =", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotEqualTo(String value) {
            addCriterion("MEMBER_TYPE <>", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeGreaterThan(String value) {
            addCriterion("MEMBER_TYPE >", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_TYPE >=", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeLessThan(String value) {
            addCriterion("MEMBER_TYPE <", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_TYPE <=", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeLike(String value) {
            addCriterion("MEMBER_TYPE like", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotLike(String value) {
            addCriterion("MEMBER_TYPE not like", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeIn(List<String> values) {
            addCriterion("MEMBER_TYPE in", values, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotIn(List<String> values) {
            addCriterion("MEMBER_TYPE not in", values, "memberType");
            return this;
        }

        public Criteria andMemberTypeBetween(String value1, String value2) {
            addCriterion("MEMBER_TYPE between", value1, value2, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotBetween(String value1, String value2) {
            addCriterion("MEMBER_TYPE not between", value1, value2, "memberType");
            return this;
        }

        public Criteria andPaperidIsNull() {
            addCriterion("PAPERID is null");
            return this;
        }

        public Criteria andPaperidIsNotNull() {
            addCriterion("PAPERID is not null");
            return this;
        }

        public Criteria andPaperidEqualTo(String value) {
            addCriterion("PAPERID =", value, "paperid");
            return this;
        }

        public Criteria andPaperidNotEqualTo(String value) {
            addCriterion("PAPERID <>", value, "paperid");
            return this;
        }

        public Criteria andPaperidGreaterThan(String value) {
            addCriterion("PAPERID >", value, "paperid");
            return this;
        }

        public Criteria andPaperidGreaterThanOrEqualTo(String value) {
            addCriterion("PAPERID >=", value, "paperid");
            return this;
        }

        public Criteria andPaperidLessThan(String value) {
            addCriterion("PAPERID <", value, "paperid");
            return this;
        }

        public Criteria andPaperidLessThanOrEqualTo(String value) {
            addCriterion("PAPERID <=", value, "paperid");
            return this;
        }

        public Criteria andPaperidLike(String value) {
            addCriterion("PAPERID like", value, "paperid");
            return this;
        }

        public Criteria andPaperidNotLike(String value) {
            addCriterion("PAPERID not like", value, "paperid");
            return this;
        }

        public Criteria andPaperidIn(List<String> values) {
            addCriterion("PAPERID in", values, "paperid");
            return this;
        }

        public Criteria andPaperidNotIn(List<String> values) {
            addCriterion("PAPERID not in", values, "paperid");
            return this;
        }

        public Criteria andPaperidBetween(String value1, String value2) {
            addCriterion("PAPERID between", value1, value2, "paperid");
            return this;
        }

        public Criteria andPaperidNotBetween(String value1, String value2) {
            addCriterion("PAPERID not between", value1, value2, "paperid");
            return this;
        }

        public Criteria andCreattimeIsNull() {
            addCriterion("CREATTIME is null");
            return this;
        }

        public Criteria andCreattimeIsNotNull() {
            addCriterion("CREATTIME is not null");
            return this;
        }

        public Criteria andCreattimeEqualTo(Date value) {
            addCriterion("CREATTIME =", value, "creattime");
            return this;
        }

        public Criteria andCreattimeNotEqualTo(Date value) {
            addCriterion("CREATTIME <>", value, "creattime");
            return this;
        }

        public Criteria andCreattimeGreaterThan(Date value) {
            addCriterion("CREATTIME >", value, "creattime");
            return this;
        }

        public Criteria andCreattimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATTIME >=", value, "creattime");
            return this;
        }

        public Criteria andCreattimeLessThan(Date value) {
            addCriterion("CREATTIME <", value, "creattime");
            return this;
        }

        public Criteria andCreattimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATTIME <=", value, "creattime");
            return this;
        }

        public Criteria andCreattimeIn(List<Date> values) {
            addCriterion("CREATTIME in", values, "creattime");
            return this;
        }

        public Criteria andCreattimeNotIn(List<Date> values) {
            addCriterion("CREATTIME not in", values, "creattime");
            return this;
        }

        public Criteria andCreattimeBetween(Date value1, Date value2) {
            addCriterion("CREATTIME between", value1, value2, "creattime");
            return this;
        }

        public Criteria andCreattimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATTIME not between", value1, value2, "creattime");
            return this;
        }

        public Criteria andEntityvalsIsNull() {
            addCriterion("ENTITYVALS is null");
            return this;
        }

        public Criteria andEntityvalsIsNotNull() {
            addCriterion("ENTITYVALS is not null");
            return this;
        }

        public Criteria andEntityvalsEqualTo(String value) {
            addCriterion("ENTITYVALS =", value, "entityvals");
            return this;
        }

        public Criteria andEntityvalsNotEqualTo(String value) {
            addCriterion("ENTITYVALS <>", value, "entityvals");
            return this;
        }

        public Criteria andEntityvalsGreaterThan(String value) {
            addCriterion("ENTITYVALS >", value, "entityvals");
            return this;
        }

        public Criteria andEntityvalsGreaterThanOrEqualTo(String value) {
            addCriterion("ENTITYVALS >=", value, "entityvals");
            return this;
        }

        public Criteria andEntityvalsLessThan(String value) {
            addCriterion("ENTITYVALS <", value, "entityvals");
            return this;
        }

        public Criteria andEntityvalsLessThanOrEqualTo(String value) {
            addCriterion("ENTITYVALS <=", value, "entityvals");
            return this;
        }

        public Criteria andEntityvalsLike(String value) {
            addCriterion("ENTITYVALS like", value, "entityvals");
            return this;
        }

        public Criteria andEntityvalsNotLike(String value) {
            addCriterion("ENTITYVALS not like", value, "entityvals");
            return this;
        }

        public Criteria andEntityvalsIn(List<String> values) {
            addCriterion("ENTITYVALS in", values, "entityvals");
            return this;
        }

        public Criteria andEntityvalsNotIn(List<String> values) {
            addCriterion("ENTITYVALS not in", values, "entityvals");
            return this;
        }

        public Criteria andEntityvalsBetween(String value1, String value2) {
            addCriterion("ENTITYVALS between", value1, value2, "entityvals");
            return this;
        }

        public Criteria andEntityvalsNotBetween(String value1, String value2) {
            addCriterion("ENTITYVALS not between", value1, value2, "entityvals");
            return this;
        }

        public Criteria andCapidIsNull() {
            addCriterion("CAPID is null");
            return this;
        }

        public Criteria andCapidIsNotNull() {
            addCriterion("CAPID is not null");
            return this;
        }

        public Criteria andCapidEqualTo(String value) {
            addCriterion("CAPID =", value, "capid");
            return this;
        }

        public Criteria andCapidNotEqualTo(String value) {
            addCriterion("CAPID <>", value, "capid");
            return this;
        }

        public Criteria andCapidGreaterThan(String value) {
            addCriterion("CAPID >", value, "capid");
            return this;
        }

        public Criteria andCapidGreaterThanOrEqualTo(String value) {
            addCriterion("CAPID >=", value, "capid");
            return this;
        }

        public Criteria andCapidLessThan(String value) {
            addCriterion("CAPID <", value, "capid");
            return this;
        }

        public Criteria andCapidLessThanOrEqualTo(String value) {
            addCriterion("CAPID <=", value, "capid");
            return this;
        }

        public Criteria andCapidLike(String value) {
            addCriterion("CAPID like", value, "capid");
            return this;
        }

        public Criteria andCapidNotLike(String value) {
            addCriterion("CAPID not like", value, "capid");
            return this;
        }

        public Criteria andCapidIn(List<String> values) {
            addCriterion("CAPID in", values, "capid");
            return this;
        }

        public Criteria andCapidNotIn(List<String> values) {
            addCriterion("CAPID not in", values, "capid");
            return this;
        }

        public Criteria andCapidBetween(String value1, String value2) {
            addCriterion("CAPID between", value1, value2, "capid");
            return this;
        }

        public Criteria andCapidNotBetween(String value1, String value2) {
            addCriterion("CAPID not between", value1, value2, "capid");
            return this;
        }

        public Criteria andYwIsNull() {
            addCriterion("YW is null");
            return this;
        }

        public Criteria andYwIsNotNull() {
            addCriterion("YW is not null");
            return this;
        }

        public Criteria andYwEqualTo(String value) {
            addCriterion("YW =", value, "yw");
            return this;
        }

        public Criteria andYwNotEqualTo(String value) {
            addCriterion("YW <>", value, "yw");
            return this;
        }

        public Criteria andYwGreaterThan(String value) {
            addCriterion("YW >", value, "yw");
            return this;
        }

        public Criteria andYwGreaterThanOrEqualTo(String value) {
            addCriterion("YW >=", value, "yw");
            return this;
        }

        public Criteria andYwLessThan(String value) {
            addCriterion("YW <", value, "yw");
            return this;
        }

        public Criteria andYwLessThanOrEqualTo(String value) {
            addCriterion("YW <=", value, "yw");
            return this;
        }

        public Criteria andYwLike(String value) {
            addCriterion("YW like", value, "yw");
            return this;
        }

        public Criteria andYwNotLike(String value) {
            addCriterion("YW not like", value, "yw");
            return this;
        }

        public Criteria andYwIn(List<String> values) {
            addCriterion("YW in", values, "yw");
            return this;
        }

        public Criteria andYwNotIn(List<String> values) {
            addCriterion("YW not in", values, "yw");
            return this;
        }

        public Criteria andYwBetween(String value1, String value2) {
            addCriterion("YW between", value1, value2, "yw");
            return this;
        }

        public Criteria andYwNotBetween(String value1, String value2) {
            addCriterion("YW not between", value1, value2, "yw");
            return this;
        }

        public Criteria andPsIsNull() {
            addCriterion("PS is null");
            return this;
        }

        public Criteria andPsIsNotNull() {
            addCriterion("PS is not null");
            return this;
        }

        public Criteria andPsEqualTo(String value) {
            addCriterion("PS =", value, "ps");
            return this;
        }

        public Criteria andPsNotEqualTo(String value) {
            addCriterion("PS <>", value, "ps");
            return this;
        }

        public Criteria andPsGreaterThan(String value) {
            addCriterion("PS >", value, "ps");
            return this;
        }

        public Criteria andPsGreaterThanOrEqualTo(String value) {
            addCriterion("PS >=", value, "ps");
            return this;
        }

        public Criteria andPsLessThan(String value) {
            addCriterion("PS <", value, "ps");
            return this;
        }

        public Criteria andPsLessThanOrEqualTo(String value) {
            addCriterion("PS <=", value, "ps");
            return this;
        }

        public Criteria andPsLike(String value) {
            addCriterion("PS like", value, "ps");
            return this;
        }

        public Criteria andPsNotLike(String value) {
            addCriterion("PS not like", value, "ps");
            return this;
        }

        public Criteria andPsIn(List<String> values) {
            addCriterion("PS in", values, "ps");
            return this;
        }

        public Criteria andPsNotIn(List<String> values) {
            addCriterion("PS not in", values, "ps");
            return this;
        }

        public Criteria andPsBetween(String value1, String value2) {
            addCriterion("PS between", value1, value2, "ps");
            return this;
        }

        public Criteria andPsNotBetween(String value1, String value2) {
            addCriterion("PS not between", value1, value2, "ps");
            return this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("AREA is null");
            return this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("AREA is not null");
            return this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("AREA =", value, "area");
            return this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("AREA <>", value, "area");
            return this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("AREA >", value, "area");
            return this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("AREA >=", value, "area");
            return this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("AREA <", value, "area");
            return this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("AREA <=", value, "area");
            return this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("AREA like", value, "area");
            return this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("AREA not like", value, "area");
            return this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("AREA in", values, "area");
            return this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("AREA not in", values, "area");
            return this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("AREA between", value1, value2, "area");
            return this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("AREA not between", value1, value2, "area");
            return this;
        }

        public Criteria andCanceltimeIsNull() {
            addCriterion("CANCELTIME is null");
            return this;
        }

        public Criteria andCanceltimeIsNotNull() {
            addCriterion("CANCELTIME is not null");
            return this;
        }

        public Criteria andCanceltimeEqualTo(Date value) {
            addCriterion("CANCELTIME =", value, "canceltime");
            return this;
        }

        public Criteria andCanceltimeNotEqualTo(Date value) {
            addCriterion("CANCELTIME <>", value, "canceltime");
            return this;
        }

        public Criteria andCanceltimeGreaterThan(Date value) {
            addCriterion("CANCELTIME >", value, "canceltime");
            return this;
        }

        public Criteria andCanceltimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CANCELTIME >=", value, "canceltime");
            return this;
        }

        public Criteria andCanceltimeLessThan(Date value) {
            addCriterion("CANCELTIME <", value, "canceltime");
            return this;
        }

        public Criteria andCanceltimeLessThanOrEqualTo(Date value) {
            addCriterion("CANCELTIME <=", value, "canceltime");
            return this;
        }

        public Criteria andCanceltimeIn(List<Date> values) {
            addCriterion("CANCELTIME in", values, "canceltime");
            return this;
        }

        public Criteria andCanceltimeNotIn(List<Date> values) {
            addCriterion("CANCELTIME not in", values, "canceltime");
            return this;
        }

        public Criteria andCanceltimeBetween(Date value1, Date value2) {
            addCriterion("CANCELTIME between", value1, value2, "canceltime");
            return this;
        }

        public Criteria andCanceltimeNotBetween(Date value1, Date value2) {
            addCriterion("CANCELTIME not between", value1, value2, "canceltime");
            return this;
        }

        public Criteria andCancelideaIsNull() {
            addCriterion("CANCELIDEA is null");
            return this;
        }

        public Criteria andCancelideaIsNotNull() {
            addCriterion("CANCELIDEA is not null");
            return this;
        }

        public Criteria andCancelideaEqualTo(String value) {
            addCriterion("CANCELIDEA =", value, "cancelidea");
            return this;
        }

        public Criteria andCancelideaNotEqualTo(String value) {
            addCriterion("CANCELIDEA <>", value, "cancelidea");
            return this;
        }

        public Criteria andCancelideaGreaterThan(String value) {
            addCriterion("CANCELIDEA >", value, "cancelidea");
            return this;
        }

        public Criteria andCancelideaGreaterThanOrEqualTo(String value) {
            addCriterion("CANCELIDEA >=", value, "cancelidea");
            return this;
        }

        public Criteria andCancelideaLessThan(String value) {
            addCriterion("CANCELIDEA <", value, "cancelidea");
            return this;
        }

        public Criteria andCancelideaLessThanOrEqualTo(String value) {
            addCriterion("CANCELIDEA <=", value, "cancelidea");
            return this;
        }

        public Criteria andCancelideaLike(String value) {
            addCriterion("CANCELIDEA like", value, "cancelidea");
            return this;
        }

        public Criteria andCancelideaNotLike(String value) {
            addCriterion("CANCELIDEA not like", value, "cancelidea");
            return this;
        }

        public Criteria andCancelideaIn(List<String> values) {
            addCriterion("CANCELIDEA in", values, "cancelidea");
            return this;
        }

        public Criteria andCancelideaNotIn(List<String> values) {
            addCriterion("CANCELIDEA not in", values, "cancelidea");
            return this;
        }

        public Criteria andCancelideaBetween(String value1, String value2) {
            addCriterion("CANCELIDEA between", value1, value2, "cancelidea");
            return this;
        }

        public Criteria andCancelideaNotBetween(String value1, String value2) {
            addCriterion("CANCELIDEA not between", value1, value2, "cancelidea");
            return this;
        }

        public Criteria andYwvalIsNull() {
            addCriterion("YWVAL is null");
            return this;
        }

        public Criteria andYwvalIsNotNull() {
            addCriterion("YWVAL is not null");
            return this;
        }

        public Criteria andYwvalEqualTo(String value) {
            addCriterion("YWVAL =", value, "ywval");
            return this;
        }

        public Criteria andYwvalNotEqualTo(String value) {
            addCriterion("YWVAL <>", value, "ywval");
            return this;
        }

        public Criteria andYwvalGreaterThan(String value) {
            addCriterion("YWVAL >", value, "ywval");
            return this;
        }

        public Criteria andYwvalGreaterThanOrEqualTo(String value) {
            addCriterion("YWVAL >=", value, "ywval");
            return this;
        }

        public Criteria andYwvalLessThan(String value) {
            addCriterion("YWVAL <", value, "ywval");
            return this;
        }

        public Criteria andYwvalLessThanOrEqualTo(String value) {
            addCriterion("YWVAL <=", value, "ywval");
            return this;
        }

        public Criteria andYwvalLike(String value) {
            addCriterion("YWVAL like", value, "ywval");
            return this;
        }

        public Criteria andYwvalNotLike(String value) {
            addCriterion("YWVAL not like", value, "ywval");
            return this;
        }

        public Criteria andYwvalIn(List<String> values) {
            addCriterion("YWVAL in", values, "ywval");
            return this;
        }

        public Criteria andYwvalNotIn(List<String> values) {
            addCriterion("YWVAL not in", values, "ywval");
            return this;
        }

        public Criteria andYwvalBetween(String value1, String value2) {
            addCriterion("YWVAL between", value1, value2, "ywval");
            return this;
        }

        public Criteria andYwvalNotBetween(String value1, String value2) {
            addCriterion("YWVAL not between", value1, value2, "ywval");
            return this;
        }
    }
}