package com.medical.model;

public class DmBizdept {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.DM_BIZDEPT.HOSPITAL_ID
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    private String hospitalId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.DM_BIZDEPT.NAME
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.DM_BIZDEPT.DEPT_TYPE
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    private String deptType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.DM_BIZDEPT.DEPT_LEVEL
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    private String deptLevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.DM_BIZDEPT.STATUS
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.DM_BIZDEPT.HOSPITAL_YB_ID
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    private String hospitalYbId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.DM_BIZDEPT.HOSPITAL_ID
     *
     * @return the value of YLJZN.DM_BIZDEPT.HOSPITAL_ID
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.DM_BIZDEPT.HOSPITAL_ID
     *
     * @param hospitalId the value for YLJZN.DM_BIZDEPT.HOSPITAL_ID
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.DM_BIZDEPT.NAME
     *
     * @return the value of YLJZN.DM_BIZDEPT.NAME
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.DM_BIZDEPT.NAME
     *
     * @param name the value for YLJZN.DM_BIZDEPT.NAME
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.DM_BIZDEPT.DEPT_TYPE
     *
     * @return the value of YLJZN.DM_BIZDEPT.DEPT_TYPE
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public String getDeptType() {
        return deptType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.DM_BIZDEPT.DEPT_TYPE
     *
     * @param deptType the value for YLJZN.DM_BIZDEPT.DEPT_TYPE
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public void setDeptType(String deptType) {
        this.deptType = deptType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.DM_BIZDEPT.DEPT_LEVEL
     *
     * @return the value of YLJZN.DM_BIZDEPT.DEPT_LEVEL
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public String getDeptLevel() {
        return deptLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.DM_BIZDEPT.DEPT_LEVEL
     *
     * @param deptLevel the value for YLJZN.DM_BIZDEPT.DEPT_LEVEL
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public void setDeptLevel(String deptLevel) {
        this.deptLevel = deptLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.DM_BIZDEPT.STATUS
     *
     * @return the value of YLJZN.DM_BIZDEPT.STATUS
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.DM_BIZDEPT.STATUS
     *
     * @param status the value for YLJZN.DM_BIZDEPT.STATUS
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.DM_BIZDEPT.HOSPITAL_YB_ID
     *
     * @return the value of YLJZN.DM_BIZDEPT.HOSPITAL_YB_ID
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public String getHospitalYbId() {
        return hospitalYbId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.DM_BIZDEPT.HOSPITAL_YB_ID
     *
     * @param hospitalYbId the value for YLJZN.DM_BIZDEPT.HOSPITAL_YB_ID
     *
     * @ibatorgenerated Wed Aug 19 10:40:02 CST 2009
     */
    public void setHospitalYbId(String hospitalYbId) {
        this.hospitalYbId = hospitalYbId;
    }
}