package com.medical.model;

import java.math.BigDecimal;

public class JzAct {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private Integer actId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.MEMBER_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private String memberId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.HOSPITAL_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private String hospitalId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.CENTER_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private String centerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_YEAR
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private Short actYear;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private String actBizType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private Short actBizTimes;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private BigDecimal actBizMoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private Short actBizInhospitalTimes;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY2
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private BigDecimal actBizMoney2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY_OLD
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private BigDecimal actBizMoneyOld;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ADD_MZ
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private BigDecimal addMz;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.ADD_ZY
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private BigDecimal addZy;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ACT.MEMBER_TYPE
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	private String memberType;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_ID
	 * @return  the value of YLJZN.JZ_ACT.ACT_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public Integer getActId() {
		return actId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_ID
	 * @param actId  the value for YLJZN.JZ_ACT.ACT_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setActId(Integer actId) {
		this.actId = actId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.MEMBER_ID
	 * @return  the value of YLJZN.JZ_ACT.MEMBER_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.MEMBER_ID
	 * @param memberId  the value for YLJZN.JZ_ACT.MEMBER_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.HOSPITAL_ID
	 * @return  the value of YLJZN.JZ_ACT.HOSPITAL_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.HOSPITAL_ID
	 * @param hospitalId  the value for YLJZN.JZ_ACT.HOSPITAL_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.CENTER_ID
	 * @return  the value of YLJZN.JZ_ACT.CENTER_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public String getCenterId() {
		return centerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.CENTER_ID
	 * @param centerId  the value for YLJZN.JZ_ACT.CENTER_ID
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setCenterId(String centerId) {
		this.centerId = centerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_YEAR
	 * @return  the value of YLJZN.JZ_ACT.ACT_YEAR
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public Short getActYear() {
		return actYear;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_YEAR
	 * @param actYear  the value for YLJZN.JZ_ACT.ACT_YEAR
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setActYear(Short actYear) {
		this.actYear = actYear;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public String getActBizType() {
		return actBizType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @param actBizType  the value for YLJZN.JZ_ACT.ACT_BIZ_TYPE
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setActBizType(String actBizType) {
		this.actBizType = actBizType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public Short getActBizTimes() {
		return actBizTimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @param actBizTimes  the value for YLJZN.JZ_ACT.ACT_BIZ_TIMES
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setActBizTimes(Short actBizTimes) {
		this.actBizTimes = actBizTimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public BigDecimal getActBizMoney() {
		return actBizMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @param actBizMoney  the value for YLJZN.JZ_ACT.ACT_BIZ_MONEY
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setActBizMoney(BigDecimal actBizMoney) {
		this.actBizMoney = actBizMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public Short getActBizInhospitalTimes() {
		return actBizInhospitalTimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @param actBizInhospitalTimes  the value for YLJZN.JZ_ACT.ACT_BIZ_INHOSPITAL_TIMES
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setActBizInhospitalTimes(Short actBizInhospitalTimes) {
		this.actBizInhospitalTimes = actBizInhospitalTimes;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY2
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_MONEY2
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public BigDecimal getActBizMoney2() {
		return actBizMoney2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY2
	 * @param actBizMoney2  the value for YLJZN.JZ_ACT.ACT_BIZ_MONEY2
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setActBizMoney2(BigDecimal actBizMoney2) {
		this.actBizMoney2 = actBizMoney2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY_OLD
	 * @return  the value of YLJZN.JZ_ACT.ACT_BIZ_MONEY_OLD
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public BigDecimal getActBizMoneyOld() {
		return actBizMoneyOld;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ACT_BIZ_MONEY_OLD
	 * @param actBizMoneyOld  the value for YLJZN.JZ_ACT.ACT_BIZ_MONEY_OLD
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setActBizMoneyOld(BigDecimal actBizMoneyOld) {
		this.actBizMoneyOld = actBizMoneyOld;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ADD_MZ
	 * @return  the value of YLJZN.JZ_ACT.ADD_MZ
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public BigDecimal getAddMz() {
		return addMz;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ADD_MZ
	 * @param addMz  the value for YLJZN.JZ_ACT.ADD_MZ
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setAddMz(BigDecimal addMz) {
		this.addMz = addMz;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.ADD_ZY
	 * @return  the value of YLJZN.JZ_ACT.ADD_ZY
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public BigDecimal getAddZy() {
		return addZy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.ADD_ZY
	 * @param addZy  the value for YLJZN.JZ_ACT.ADD_ZY
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setAddZy(BigDecimal addZy) {
		this.addZy = addZy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ACT.MEMBER_TYPE
	 * @return  the value of YLJZN.JZ_ACT.MEMBER_TYPE
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public String getMemberType() {
		return memberType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ACT.MEMBER_TYPE
	 * @param memberType  the value for YLJZN.JZ_ACT.MEMBER_TYPE
	 * @ibatorgenerated  Sun Nov 16 04:02:36 CST 2014
	 */
	public void setMemberType(String memberType) {
		this.memberType = memberType;
	}
}
