package com.medical.model;

import java.math.BigDecimal;
import java.util.Date;

public class JzAspapprove {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.ASPAPPROVE_ID
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private BigDecimal aspapproveId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.FAMILY_ID
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String familyId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.NAME
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.SSN
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String ssn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.ENTITY
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Integer entity;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.STATUS
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Short status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.FLAG
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Short flag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRRESULT1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Short aprresult1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRIDEA1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String apridea1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRTIME1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Date aprtime1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRPERSON1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String aprperson1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRRESULT2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Short aprresult2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRIDEA2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String apridea2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRTIME2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Date aprtime2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRPERSON2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String aprperson2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRRESULT3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Short aprresult3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRIDEA3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String apridea3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRTIME3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Date aprtime3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRPERSON3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String aprperson3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRLEVEL
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Short aprlevel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.APRMEDICAL
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String aprmedical;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.MEMBER_ID
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String memberId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.PRINTCOUNT
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private Short printcount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_ASPAPPROVE.MEMBERTYPE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	private String membertype;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.ASPAPPROVE_ID
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.ASPAPPROVE_ID
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public BigDecimal getAspapproveId() {
		return aspapproveId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.ASPAPPROVE_ID
	 * @param aspapproveId  the value for YLJZN.JZ_ASPAPPROVE.ASPAPPROVE_ID
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAspapproveId(BigDecimal aspapproveId) {
		this.aspapproveId = aspapproveId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.FAMILY_ID
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.FAMILY_ID
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getFamilyId() {
		return familyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.FAMILY_ID
	 * @param familyId  the value for YLJZN.JZ_ASPAPPROVE.FAMILY_ID
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setFamilyId(String familyId) {
		this.familyId = familyId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.NAME
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.NAME
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.NAME
	 * @param name  the value for YLJZN.JZ_ASPAPPROVE.NAME
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.SSN
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.SSN
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getSsn() {
		return ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.SSN
	 * @param ssn  the value for YLJZN.JZ_ASPAPPROVE.SSN
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.ENTITY
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.ENTITY
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Integer getEntity() {
		return entity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.ENTITY
	 * @param entity  the value for YLJZN.JZ_ASPAPPROVE.ENTITY
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setEntity(Integer entity) {
		this.entity = entity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.STATUS
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.STATUS
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.STATUS
	 * @param status  the value for YLJZN.JZ_ASPAPPROVE.STATUS
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.FLAG
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.FLAG
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Short getFlag() {
		return flag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.FLAG
	 * @param flag  the value for YLJZN.JZ_ASPAPPROVE.FLAG
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setFlag(Short flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRRESULT1
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRRESULT1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Short getAprresult1() {
		return aprresult1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRRESULT1
	 * @param aprresult1  the value for YLJZN.JZ_ASPAPPROVE.APRRESULT1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprresult1(Short aprresult1) {
		this.aprresult1 = aprresult1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRIDEA1
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRIDEA1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getApridea1() {
		return apridea1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRIDEA1
	 * @param apridea1  the value for YLJZN.JZ_ASPAPPROVE.APRIDEA1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setApridea1(String apridea1) {
		this.apridea1 = apridea1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRTIME1
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRTIME1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Date getAprtime1() {
		return aprtime1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRTIME1
	 * @param aprtime1  the value for YLJZN.JZ_ASPAPPROVE.APRTIME1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprtime1(Date aprtime1) {
		this.aprtime1 = aprtime1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRPERSON1
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRPERSON1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getAprperson1() {
		return aprperson1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRPERSON1
	 * @param aprperson1  the value for YLJZN.JZ_ASPAPPROVE.APRPERSON1
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprperson1(String aprperson1) {
		this.aprperson1 = aprperson1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRRESULT2
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRRESULT2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Short getAprresult2() {
		return aprresult2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRRESULT2
	 * @param aprresult2  the value for YLJZN.JZ_ASPAPPROVE.APRRESULT2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprresult2(Short aprresult2) {
		this.aprresult2 = aprresult2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRIDEA2
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRIDEA2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getApridea2() {
		return apridea2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRIDEA2
	 * @param apridea2  the value for YLJZN.JZ_ASPAPPROVE.APRIDEA2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setApridea2(String apridea2) {
		this.apridea2 = apridea2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRTIME2
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRTIME2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Date getAprtime2() {
		return aprtime2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRTIME2
	 * @param aprtime2  the value for YLJZN.JZ_ASPAPPROVE.APRTIME2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprtime2(Date aprtime2) {
		this.aprtime2 = aprtime2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRPERSON2
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRPERSON2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getAprperson2() {
		return aprperson2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRPERSON2
	 * @param aprperson2  the value for YLJZN.JZ_ASPAPPROVE.APRPERSON2
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprperson2(String aprperson2) {
		this.aprperson2 = aprperson2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRRESULT3
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRRESULT3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Short getAprresult3() {
		return aprresult3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRRESULT3
	 * @param aprresult3  the value for YLJZN.JZ_ASPAPPROVE.APRRESULT3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprresult3(Short aprresult3) {
		this.aprresult3 = aprresult3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRIDEA3
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRIDEA3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getApridea3() {
		return apridea3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRIDEA3
	 * @param apridea3  the value for YLJZN.JZ_ASPAPPROVE.APRIDEA3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setApridea3(String apridea3) {
		this.apridea3 = apridea3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRTIME3
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRTIME3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Date getAprtime3() {
		return aprtime3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRTIME3
	 * @param aprtime3  the value for YLJZN.JZ_ASPAPPROVE.APRTIME3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprtime3(Date aprtime3) {
		this.aprtime3 = aprtime3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRPERSON3
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRPERSON3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getAprperson3() {
		return aprperson3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRPERSON3
	 * @param aprperson3  the value for YLJZN.JZ_ASPAPPROVE.APRPERSON3
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprperson3(String aprperson3) {
		this.aprperson3 = aprperson3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRLEVEL
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRLEVEL
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Short getAprlevel() {
		return aprlevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRLEVEL
	 * @param aprlevel  the value for YLJZN.JZ_ASPAPPROVE.APRLEVEL
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprlevel(Short aprlevel) {
		this.aprlevel = aprlevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.APRMEDICAL
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.APRMEDICAL
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getAprmedical() {
		return aprmedical;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.APRMEDICAL
	 * @param aprmedical  the value for YLJZN.JZ_ASPAPPROVE.APRMEDICAL
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setAprmedical(String aprmedical) {
		this.aprmedical = aprmedical;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.MEMBER_ID
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.MEMBER_ID
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.MEMBER_ID
	 * @param memberId  the value for YLJZN.JZ_ASPAPPROVE.MEMBER_ID
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.PRINTCOUNT
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.PRINTCOUNT
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public Short getPrintcount() {
		return printcount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.PRINTCOUNT
	 * @param printcount  the value for YLJZN.JZ_ASPAPPROVE.PRINTCOUNT
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setPrintcount(Short printcount) {
		this.printcount = printcount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_ASPAPPROVE.MEMBERTYPE
	 * @return  the value of YLJZN.JZ_ASPAPPROVE.MEMBERTYPE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public String getMembertype() {
		return membertype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_ASPAPPROVE.MEMBERTYPE
	 * @param membertype  the value for YLJZN.JZ_ASPAPPROVE.MEMBERTYPE
	 * @ibatorgenerated  Mon Nov 22 14:57:13 CST 2010
	 */
	public void setMembertype(String membertype) {
		this.membertype = membertype;
	}
}