package com.medical.model;

import java.math.BigDecimal;
import java.util.Date;

public class JzBizHistory {

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.JBH_ID
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private Integer jbhId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.BIZ_ID
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private BigDecimal bizId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.OPERTYPE
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private BigDecimal opertype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.OPERUID
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private BigDecimal operuid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.TOTALMONEY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private BigDecimal totalmoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.PERSONACC
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private BigDecimal personacc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.INSURANCEPAY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private BigDecimal insurancepay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.ASSISTMONEY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private BigDecimal assistmoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.REALPAY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private BigDecimal realpay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ_HISTORY.OPERTIME
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    private Date opertime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.JBH_ID
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.JBH_ID
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public Integer getJbhId() {
        return jbhId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.JBH_ID
     *
     * @param jbhId the value for YLJZN.JZ_BIZ_HISTORY.JBH_ID
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setJbhId(Integer jbhId) {
        this.jbhId = jbhId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.BIZ_ID
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.BIZ_ID
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public BigDecimal getBizId() {
        return bizId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.BIZ_ID
     *
     * @param bizId the value for YLJZN.JZ_BIZ_HISTORY.BIZ_ID
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setBizId(BigDecimal bizId) {
        this.bizId = bizId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.OPERTYPE
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.OPERTYPE
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public BigDecimal getOpertype() {
        return opertype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.OPERTYPE
     *
     * @param opertype the value for YLJZN.JZ_BIZ_HISTORY.OPERTYPE
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setOpertype(BigDecimal opertype) {
        this.opertype = opertype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.OPERUID
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.OPERUID
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public BigDecimal getOperuid() {
        return operuid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.OPERUID
     *
     * @param operuid the value for YLJZN.JZ_BIZ_HISTORY.OPERUID
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setOperuid(BigDecimal operuid) {
        this.operuid = operuid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.TOTALMONEY
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.TOTALMONEY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public BigDecimal getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.TOTALMONEY
     *
     * @param totalmoney the value for YLJZN.JZ_BIZ_HISTORY.TOTALMONEY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setTotalmoney(BigDecimal totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.PERSONACC
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.PERSONACC
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public BigDecimal getPersonacc() {
        return personacc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.PERSONACC
     *
     * @param personacc the value for YLJZN.JZ_BIZ_HISTORY.PERSONACC
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setPersonacc(BigDecimal personacc) {
        this.personacc = personacc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.INSURANCEPAY
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.INSURANCEPAY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public BigDecimal getInsurancepay() {
        return insurancepay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.INSURANCEPAY
     *
     * @param insurancepay the value for YLJZN.JZ_BIZ_HISTORY.INSURANCEPAY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setInsurancepay(BigDecimal insurancepay) {
        this.insurancepay = insurancepay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.ASSISTMONEY
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.ASSISTMONEY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public BigDecimal getAssistmoney() {
        return assistmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.ASSISTMONEY
     *
     * @param assistmoney the value for YLJZN.JZ_BIZ_HISTORY.ASSISTMONEY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setAssistmoney(BigDecimal assistmoney) {
        this.assistmoney = assistmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.REALPAY
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.REALPAY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public BigDecimal getRealpay() {
        return realpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.REALPAY
     *
     * @param realpay the value for YLJZN.JZ_BIZ_HISTORY.REALPAY
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setRealpay(BigDecimal realpay) {
        this.realpay = realpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ_HISTORY.OPERTIME
     *
     * @return the value of YLJZN.JZ_BIZ_HISTORY.OPERTIME
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ_HISTORY.OPERTIME
     *
     * @param opertime the value for YLJZN.JZ_BIZ_HISTORY.OPERTIME
     *
     * @ibatorgenerated Fri Nov 13 10:26:12 CST 2009
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }
}
