package com.medical.model;

import java.math.BigDecimal;
import java.util.Date;

public class JzBiz {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.BIZ_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Integer bizId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.HOSPITAL_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String hospitalId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.CENTER_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String centerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.BIZ_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String bizType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.BIZ_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String bizName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.SERIAL_NO
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String serialNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.SSN
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String ssn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.FAMILY_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String familyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.SEX
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.BIRTHDAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Date birthday;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.IDCARD
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String idcard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.TREATMENT_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String treatmentType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.TREATMENT_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String treatmentName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.BIZ_TIMES
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Short bizTimes;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.REG_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Date regDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.BEGIN_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Date beginDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.IN_DEPT_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String inDeptName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.IN_AREA_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String inAreaName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.IN_BED
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String inBed;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.IN_DISEASE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String inDisease;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.IN_DISEASE_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String inDiseaseName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.DIAGNOSE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String diagnose;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.DIAGNOSE_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String diagnoseName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.DIAGNOSE_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Date diagnoseDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.FIN_DISEASE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String finDisease;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.FIN_DISEASE_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String finDiseaseName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.END_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Date endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.OUT_DEPT_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String outDeptName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.COMPLICATIONS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String complications;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.IN_DAYS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Short inDays;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.ASSIST_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String assistType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.STAUS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String staus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.PATIENT_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String patientId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.FIN_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Date finDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.INMONEY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal inmoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.OPERUID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal operuid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.OPERTIME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Date opertime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.ASSIST_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String assistFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.PHOTOPATH
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String photopath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.ALLMONEY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal allmoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.PERSONPAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal personpay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.INSURANCEPAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal insurancepay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.ASSISTPAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal assistpay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.ASSISTPAYMSG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String assistpaymsg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.PHOTOPATH2
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String photopath2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.CONFIRM_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String confirmFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.IN_MONEY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal inMoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.PERSON_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String personType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.FEE_BATCH
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Integer feeBatch;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.OUT_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Short outFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.ALREADY_GET
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Short alreadyGet;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.GATHER_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String gatherFlag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.SMS_STATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal smsState;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.CHECK_STATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal checkState;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.ESTIMATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private BigDecimal estimate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.OUTHOSPITALNAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String outhospitalname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.INHOSPITALNAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String inhospitalname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.INHOSPTIME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Date inhosptime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.OUTHOSPTIME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private Date outhosptime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.CAUSEDECS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String causedecs;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_BIZ.HOSPITAL_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    private String hospitalName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.BIZ_ID
     *
     * @return the value of YLJZN.JZ_BIZ.BIZ_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Integer getBizId() {
        return bizId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.BIZ_ID
     *
     * @param bizId the value for YLJZN.JZ_BIZ.BIZ_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setBizId(Integer bizId) {
        this.bizId = bizId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.HOSPITAL_ID
     *
     * @return the value of YLJZN.JZ_BIZ.HOSPITAL_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.HOSPITAL_ID
     *
     * @param hospitalId the value for YLJZN.JZ_BIZ.HOSPITAL_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.CENTER_ID
     *
     * @return the value of YLJZN.JZ_BIZ.CENTER_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getCenterId() {
        return centerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.CENTER_ID
     *
     * @param centerId the value for YLJZN.JZ_BIZ.CENTER_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setCenterId(String centerId) {
        this.centerId = centerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.BIZ_TYPE
     *
     * @return the value of YLJZN.JZ_BIZ.BIZ_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.BIZ_TYPE
     *
     * @param bizType the value for YLJZN.JZ_BIZ.BIZ_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setBizType(String bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.BIZ_NAME
     *
     * @return the value of YLJZN.JZ_BIZ.BIZ_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.BIZ_NAME
     *
     * @param bizName the value for YLJZN.JZ_BIZ.BIZ_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setBizName(String bizName) {
        this.bizName = bizName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.SERIAL_NO
     *
     * @return the value of YLJZN.JZ_BIZ.SERIAL_NO
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.SERIAL_NO
     *
     * @param serialNo the value for YLJZN.JZ_BIZ.SERIAL_NO
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.SSN
     *
     * @return the value of YLJZN.JZ_BIZ.SSN
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.SSN
     *
     * @param ssn the value for YLJZN.JZ_BIZ.SSN
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.FAMILY_ID
     *
     * @return the value of YLJZN.JZ_BIZ.FAMILY_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.FAMILY_ID
     *
     * @param familyId the value for YLJZN.JZ_BIZ.FAMILY_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setFamilyId(String familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.NAME
     *
     * @return the value of YLJZN.JZ_BIZ.NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.NAME
     *
     * @param name the value for YLJZN.JZ_BIZ.NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.SEX
     *
     * @return the value of YLJZN.JZ_BIZ.SEX
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.SEX
     *
     * @param sex the value for YLJZN.JZ_BIZ.SEX
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.BIRTHDAY
     *
     * @return the value of YLJZN.JZ_BIZ.BIRTHDAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.BIRTHDAY
     *
     * @param birthday the value for YLJZN.JZ_BIZ.BIRTHDAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.IDCARD
     *
     * @return the value of YLJZN.JZ_BIZ.IDCARD
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.IDCARD
     *
     * @param idcard the value for YLJZN.JZ_BIZ.IDCARD
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.TREATMENT_TYPE
     *
     * @return the value of YLJZN.JZ_BIZ.TREATMENT_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getTreatmentType() {
        return treatmentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.TREATMENT_TYPE
     *
     * @param treatmentType the value for YLJZN.JZ_BIZ.TREATMENT_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setTreatmentType(String treatmentType) {
        this.treatmentType = treatmentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.TREATMENT_NAME
     *
     * @return the value of YLJZN.JZ_BIZ.TREATMENT_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getTreatmentName() {
        return treatmentName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.TREATMENT_NAME
     *
     * @param treatmentName the value for YLJZN.JZ_BIZ.TREATMENT_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setTreatmentName(String treatmentName) {
        this.treatmentName = treatmentName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.BIZ_TIMES
     *
     * @return the value of YLJZN.JZ_BIZ.BIZ_TIMES
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Short getBizTimes() {
        return bizTimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.BIZ_TIMES
     *
     * @param bizTimes the value for YLJZN.JZ_BIZ.BIZ_TIMES
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setBizTimes(Short bizTimes) {
        this.bizTimes = bizTimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.REG_DATE
     *
     * @return the value of YLJZN.JZ_BIZ.REG_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.REG_DATE
     *
     * @param regDate the value for YLJZN.JZ_BIZ.REG_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.BEGIN_DATE
     *
     * @return the value of YLJZN.JZ_BIZ.BEGIN_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.BEGIN_DATE
     *
     * @param beginDate the value for YLJZN.JZ_BIZ.BEGIN_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.IN_DEPT_NAME
     *
     * @return the value of YLJZN.JZ_BIZ.IN_DEPT_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getInDeptName() {
        return inDeptName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.IN_DEPT_NAME
     *
     * @param inDeptName the value for YLJZN.JZ_BIZ.IN_DEPT_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInDeptName(String inDeptName) {
        this.inDeptName = inDeptName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.IN_AREA_NAME
     *
     * @return the value of YLJZN.JZ_BIZ.IN_AREA_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getInAreaName() {
        return inAreaName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.IN_AREA_NAME
     *
     * @param inAreaName the value for YLJZN.JZ_BIZ.IN_AREA_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInAreaName(String inAreaName) {
        this.inAreaName = inAreaName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.IN_BED
     *
     * @return the value of YLJZN.JZ_BIZ.IN_BED
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getInBed() {
        return inBed;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.IN_BED
     *
     * @param inBed the value for YLJZN.JZ_BIZ.IN_BED
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInBed(String inBed) {
        this.inBed = inBed;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.IN_DISEASE
     *
     * @return the value of YLJZN.JZ_BIZ.IN_DISEASE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getInDisease() {
        return inDisease;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.IN_DISEASE
     *
     * @param inDisease the value for YLJZN.JZ_BIZ.IN_DISEASE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInDisease(String inDisease) {
        this.inDisease = inDisease;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.IN_DISEASE_NAME
     *
     * @return the value of YLJZN.JZ_BIZ.IN_DISEASE_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getInDiseaseName() {
        return inDiseaseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.IN_DISEASE_NAME
     *
     * @param inDiseaseName the value for YLJZN.JZ_BIZ.IN_DISEASE_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInDiseaseName(String inDiseaseName) {
        this.inDiseaseName = inDiseaseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.DIAGNOSE
     *
     * @return the value of YLJZN.JZ_BIZ.DIAGNOSE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getDiagnose() {
        return diagnose;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.DIAGNOSE
     *
     * @param diagnose the value for YLJZN.JZ_BIZ.DIAGNOSE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setDiagnose(String diagnose) {
        this.diagnose = diagnose;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.DIAGNOSE_NAME
     *
     * @return the value of YLJZN.JZ_BIZ.DIAGNOSE_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getDiagnoseName() {
        return diagnoseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.DIAGNOSE_NAME
     *
     * @param diagnoseName the value for YLJZN.JZ_BIZ.DIAGNOSE_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setDiagnoseName(String diagnoseName) {
        this.diagnoseName = diagnoseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.DIAGNOSE_DATE
     *
     * @return the value of YLJZN.JZ_BIZ.DIAGNOSE_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Date getDiagnoseDate() {
        return diagnoseDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.DIAGNOSE_DATE
     *
     * @param diagnoseDate the value for YLJZN.JZ_BIZ.DIAGNOSE_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setDiagnoseDate(Date diagnoseDate) {
        this.diagnoseDate = diagnoseDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.FIN_DISEASE
     *
     * @return the value of YLJZN.JZ_BIZ.FIN_DISEASE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getFinDisease() {
        return finDisease;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.FIN_DISEASE
     *
     * @param finDisease the value for YLJZN.JZ_BIZ.FIN_DISEASE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setFinDisease(String finDisease) {
        this.finDisease = finDisease;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.FIN_DISEASE_NAME
     *
     * @return the value of YLJZN.JZ_BIZ.FIN_DISEASE_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getFinDiseaseName() {
        return finDiseaseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.FIN_DISEASE_NAME
     *
     * @param finDiseaseName the value for YLJZN.JZ_BIZ.FIN_DISEASE_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setFinDiseaseName(String finDiseaseName) {
        this.finDiseaseName = finDiseaseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.END_DATE
     *
     * @return the value of YLJZN.JZ_BIZ.END_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.END_DATE
     *
     * @param endDate the value for YLJZN.JZ_BIZ.END_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.OUT_DEPT_NAME
     *
     * @return the value of YLJZN.JZ_BIZ.OUT_DEPT_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getOutDeptName() {
        return outDeptName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.OUT_DEPT_NAME
     *
     * @param outDeptName the value for YLJZN.JZ_BIZ.OUT_DEPT_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setOutDeptName(String outDeptName) {
        this.outDeptName = outDeptName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.COMPLICATIONS
     *
     * @return the value of YLJZN.JZ_BIZ.COMPLICATIONS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getComplications() {
        return complications;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.COMPLICATIONS
     *
     * @param complications the value for YLJZN.JZ_BIZ.COMPLICATIONS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setComplications(String complications) {
        this.complications = complications;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.IN_DAYS
     *
     * @return the value of YLJZN.JZ_BIZ.IN_DAYS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Short getInDays() {
        return inDays;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.IN_DAYS
     *
     * @param inDays the value for YLJZN.JZ_BIZ.IN_DAYS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInDays(Short inDays) {
        this.inDays = inDays;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.ASSIST_TYPE
     *
     * @return the value of YLJZN.JZ_BIZ.ASSIST_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getAssistType() {
        return assistType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.ASSIST_TYPE
     *
     * @param assistType the value for YLJZN.JZ_BIZ.ASSIST_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setAssistType(String assistType) {
        this.assistType = assistType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.STAUS
     *
     * @return the value of YLJZN.JZ_BIZ.STAUS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getStaus() {
        return staus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.STAUS
     *
     * @param staus the value for YLJZN.JZ_BIZ.STAUS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setStaus(String staus) {
        this.staus = staus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.PATIENT_ID
     *
     * @return the value of YLJZN.JZ_BIZ.PATIENT_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.PATIENT_ID
     *
     * @param patientId the value for YLJZN.JZ_BIZ.PATIENT_ID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.FIN_DATE
     *
     * @return the value of YLJZN.JZ_BIZ.FIN_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Date getFinDate() {
        return finDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.FIN_DATE
     *
     * @param finDate the value for YLJZN.JZ_BIZ.FIN_DATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setFinDate(Date finDate) {
        this.finDate = finDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.INMONEY
     *
     * @return the value of YLJZN.JZ_BIZ.INMONEY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getInmoney() {
        return inmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.INMONEY
     *
     * @param inmoney the value for YLJZN.JZ_BIZ.INMONEY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInmoney(BigDecimal inmoney) {
        this.inmoney = inmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.OPERUID
     *
     * @return the value of YLJZN.JZ_BIZ.OPERUID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getOperuid() {
        return operuid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.OPERUID
     *
     * @param operuid the value for YLJZN.JZ_BIZ.OPERUID
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setOperuid(BigDecimal operuid) {
        this.operuid = operuid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.OPERTIME
     *
     * @return the value of YLJZN.JZ_BIZ.OPERTIME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.OPERTIME
     *
     * @param opertime the value for YLJZN.JZ_BIZ.OPERTIME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.ASSIST_FLAG
     *
     * @return the value of YLJZN.JZ_BIZ.ASSIST_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getAssistFlag() {
        return assistFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.ASSIST_FLAG
     *
     * @param assistFlag the value for YLJZN.JZ_BIZ.ASSIST_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setAssistFlag(String assistFlag) {
        this.assistFlag = assistFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.PHOTOPATH
     *
     * @return the value of YLJZN.JZ_BIZ.PHOTOPATH
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getPhotopath() {
        return photopath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.PHOTOPATH
     *
     * @param photopath the value for YLJZN.JZ_BIZ.PHOTOPATH
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setPhotopath(String photopath) {
        this.photopath = photopath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.ALLMONEY
     *
     * @return the value of YLJZN.JZ_BIZ.ALLMONEY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getAllmoney() {
        return allmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.ALLMONEY
     *
     * @param allmoney the value for YLJZN.JZ_BIZ.ALLMONEY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setAllmoney(BigDecimal allmoney) {
        this.allmoney = allmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.PERSONPAY
     *
     * @return the value of YLJZN.JZ_BIZ.PERSONPAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getPersonpay() {
        return personpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.PERSONPAY
     *
     * @param personpay the value for YLJZN.JZ_BIZ.PERSONPAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setPersonpay(BigDecimal personpay) {
        this.personpay = personpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.INSURANCEPAY
     *
     * @return the value of YLJZN.JZ_BIZ.INSURANCEPAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getInsurancepay() {
        return insurancepay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.INSURANCEPAY
     *
     * @param insurancepay the value for YLJZN.JZ_BIZ.INSURANCEPAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInsurancepay(BigDecimal insurancepay) {
        this.insurancepay = insurancepay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.ASSISTPAY
     *
     * @return the value of YLJZN.JZ_BIZ.ASSISTPAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getAssistpay() {
        return assistpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.ASSISTPAY
     *
     * @param assistpay the value for YLJZN.JZ_BIZ.ASSISTPAY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setAssistpay(BigDecimal assistpay) {
        this.assistpay = assistpay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.ASSISTPAYMSG
     *
     * @return the value of YLJZN.JZ_BIZ.ASSISTPAYMSG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getAssistpaymsg() {
        return assistpaymsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.ASSISTPAYMSG
     *
     * @param assistpaymsg the value for YLJZN.JZ_BIZ.ASSISTPAYMSG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setAssistpaymsg(String assistpaymsg) {
        this.assistpaymsg = assistpaymsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.PHOTOPATH2
     *
     * @return the value of YLJZN.JZ_BIZ.PHOTOPATH2
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getPhotopath2() {
        return photopath2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.PHOTOPATH2
     *
     * @param photopath2 the value for YLJZN.JZ_BIZ.PHOTOPATH2
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setPhotopath2(String photopath2) {
        this.photopath2 = photopath2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.CONFIRM_FLAG
     *
     * @return the value of YLJZN.JZ_BIZ.CONFIRM_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getConfirmFlag() {
        return confirmFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.CONFIRM_FLAG
     *
     * @param confirmFlag the value for YLJZN.JZ_BIZ.CONFIRM_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setConfirmFlag(String confirmFlag) {
        this.confirmFlag = confirmFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.IN_MONEY
     *
     * @return the value of YLJZN.JZ_BIZ.IN_MONEY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getInMoney() {
        return inMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.IN_MONEY
     *
     * @param inMoney the value for YLJZN.JZ_BIZ.IN_MONEY
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInMoney(BigDecimal inMoney) {
        this.inMoney = inMoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.PERSON_TYPE
     *
     * @return the value of YLJZN.JZ_BIZ.PERSON_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getPersonType() {
        return personType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.PERSON_TYPE
     *
     * @param personType the value for YLJZN.JZ_BIZ.PERSON_TYPE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setPersonType(String personType) {
        this.personType = personType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.FEE_BATCH
     *
     * @return the value of YLJZN.JZ_BIZ.FEE_BATCH
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Integer getFeeBatch() {
        return feeBatch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.FEE_BATCH
     *
     * @param feeBatch the value for YLJZN.JZ_BIZ.FEE_BATCH
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setFeeBatch(Integer feeBatch) {
        this.feeBatch = feeBatch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.OUT_FLAG
     *
     * @return the value of YLJZN.JZ_BIZ.OUT_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Short getOutFlag() {
        return outFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.OUT_FLAG
     *
     * @param outFlag the value for YLJZN.JZ_BIZ.OUT_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setOutFlag(Short outFlag) {
        this.outFlag = outFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.ALREADY_GET
     *
     * @return the value of YLJZN.JZ_BIZ.ALREADY_GET
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Short getAlreadyGet() {
        return alreadyGet;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.ALREADY_GET
     *
     * @param alreadyGet the value for YLJZN.JZ_BIZ.ALREADY_GET
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setAlreadyGet(Short alreadyGet) {
        this.alreadyGet = alreadyGet;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.GATHER_FLAG
     *
     * @return the value of YLJZN.JZ_BIZ.GATHER_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getGatherFlag() {
        return gatherFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.GATHER_FLAG
     *
     * @param gatherFlag the value for YLJZN.JZ_BIZ.GATHER_FLAG
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setGatherFlag(String gatherFlag) {
        this.gatherFlag = gatherFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.SMS_STATE
     *
     * @return the value of YLJZN.JZ_BIZ.SMS_STATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getSmsState() {
        return smsState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.SMS_STATE
     *
     * @param smsState the value for YLJZN.JZ_BIZ.SMS_STATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setSmsState(BigDecimal smsState) {
        this.smsState = smsState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.CHECK_STATE
     *
     * @return the value of YLJZN.JZ_BIZ.CHECK_STATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getCheckState() {
        return checkState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.CHECK_STATE
     *
     * @param checkState the value for YLJZN.JZ_BIZ.CHECK_STATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setCheckState(BigDecimal checkState) {
        this.checkState = checkState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.ESTIMATE
     *
     * @return the value of YLJZN.JZ_BIZ.ESTIMATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public BigDecimal getEstimate() {
        return estimate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.ESTIMATE
     *
     * @param estimate the value for YLJZN.JZ_BIZ.ESTIMATE
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setEstimate(BigDecimal estimate) {
        this.estimate = estimate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.OUTHOSPITALNAME
     *
     * @return the value of YLJZN.JZ_BIZ.OUTHOSPITALNAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getOuthospitalname() {
        return outhospitalname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.OUTHOSPITALNAME
     *
     * @param outhospitalname the value for YLJZN.JZ_BIZ.OUTHOSPITALNAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setOuthospitalname(String outhospitalname) {
        this.outhospitalname = outhospitalname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.INHOSPITALNAME
     *
     * @return the value of YLJZN.JZ_BIZ.INHOSPITALNAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getInhospitalname() {
        return inhospitalname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.INHOSPITALNAME
     *
     * @param inhospitalname the value for YLJZN.JZ_BIZ.INHOSPITALNAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInhospitalname(String inhospitalname) {
        this.inhospitalname = inhospitalname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.INHOSPTIME
     *
     * @return the value of YLJZN.JZ_BIZ.INHOSPTIME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Date getInhosptime() {
        return inhosptime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.INHOSPTIME
     *
     * @param inhosptime the value for YLJZN.JZ_BIZ.INHOSPTIME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setInhosptime(Date inhosptime) {
        this.inhosptime = inhosptime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.OUTHOSPTIME
     *
     * @return the value of YLJZN.JZ_BIZ.OUTHOSPTIME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public Date getOuthosptime() {
        return outhosptime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.OUTHOSPTIME
     *
     * @param outhosptime the value for YLJZN.JZ_BIZ.OUTHOSPTIME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setOuthosptime(Date outhosptime) {
        this.outhosptime = outhosptime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.CAUSEDECS
     *
     * @return the value of YLJZN.JZ_BIZ.CAUSEDECS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getCausedecs() {
        return causedecs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.CAUSEDECS
     *
     * @param causedecs the value for YLJZN.JZ_BIZ.CAUSEDECS
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setCausedecs(String causedecs) {
        this.causedecs = causedecs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_BIZ.HOSPITAL_NAME
     *
     * @return the value of YLJZN.JZ_BIZ.HOSPITAL_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_BIZ.HOSPITAL_NAME
     *
     * @param hospitalName the value for YLJZN.JZ_BIZ.HOSPITAL_NAME
     *
     * @ibatorgenerated Fri Nov 13 14:00:19 CST 2009
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }
}