package com.medical.model;

import java.math.BigDecimal;
import java.util.Date;

public class JzChronicapprove {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.CHRONICAPPROVE_ID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private BigDecimal chronicapproveId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.FAMILY_ID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String familyId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.NAME
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.SSN
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String ssn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.ENTITY
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Integer entity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.STATUS
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Short status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.FLAG
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Short flag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRRESULT1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Short aprresult1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRIDEA1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String apridea1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRTIME1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Date aprtime1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRPERSON1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String aprperson1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRRESULT2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Short aprresult2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRIDEA2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String apridea2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRTIME2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Date aprtime2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRPERSON2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String aprperson2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRRESULT3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Short aprresult3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRIDEA3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String apridea3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRTIME3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Date aprtime3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRPERSON3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String aprperson3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.APRLEVEL
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Short aprlevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.MEMBER_ID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String memberId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.MEMBER_TYPE
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String memberType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.CANCELIDEA
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String cancelidea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.CANCELTIME
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private Date canceltime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.ENTITYS
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String entitys;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.ENTITYVAL
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String entityval;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.PAPERID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String paperid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.AREA
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String area;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.YW
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String yw;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.JZ_CHRONICAPPROVE.PS
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    private String ps;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.CHRONICAPPROVE_ID
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.CHRONICAPPROVE_ID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public BigDecimal getChronicapproveId() {
        return chronicapproveId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.CHRONICAPPROVE_ID
     *
     * @param chronicapproveId the value for YLJZN.JZ_CHRONICAPPROVE.CHRONICAPPROVE_ID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setChronicapproveId(BigDecimal chronicapproveId) {
        this.chronicapproveId = chronicapproveId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.FAMILY_ID
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.FAMILY_ID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.FAMILY_ID
     *
     * @param familyId the value for YLJZN.JZ_CHRONICAPPROVE.FAMILY_ID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setFamilyId(String familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.NAME
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.NAME
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.NAME
     *
     * @param name the value for YLJZN.JZ_CHRONICAPPROVE.NAME
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.SSN
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.SSN
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.SSN
     *
     * @param ssn the value for YLJZN.JZ_CHRONICAPPROVE.SSN
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.ENTITY
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.ENTITY
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Integer getEntity() {
        return entity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.ENTITY
     *
     * @param entity the value for YLJZN.JZ_CHRONICAPPROVE.ENTITY
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setEntity(Integer entity) {
        this.entity = entity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.STATUS
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.STATUS
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.STATUS
     *
     * @param status the value for YLJZN.JZ_CHRONICAPPROVE.STATUS
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.FLAG
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.FLAG
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Short getFlag() {
        return flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.FLAG
     *
     * @param flag the value for YLJZN.JZ_CHRONICAPPROVE.FLAG
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setFlag(Short flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRRESULT1
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRRESULT1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Short getAprresult1() {
        return aprresult1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRRESULT1
     *
     * @param aprresult1 the value for YLJZN.JZ_CHRONICAPPROVE.APRRESULT1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprresult1(Short aprresult1) {
        this.aprresult1 = aprresult1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRIDEA1
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRIDEA1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getApridea1() {
        return apridea1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRIDEA1
     *
     * @param apridea1 the value for YLJZN.JZ_CHRONICAPPROVE.APRIDEA1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setApridea1(String apridea1) {
        this.apridea1 = apridea1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRTIME1
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRTIME1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Date getAprtime1() {
        return aprtime1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRTIME1
     *
     * @param aprtime1 the value for YLJZN.JZ_CHRONICAPPROVE.APRTIME1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprtime1(Date aprtime1) {
        this.aprtime1 = aprtime1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRPERSON1
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRPERSON1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getAprperson1() {
        return aprperson1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRPERSON1
     *
     * @param aprperson1 the value for YLJZN.JZ_CHRONICAPPROVE.APRPERSON1
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprperson1(String aprperson1) {
        this.aprperson1 = aprperson1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRRESULT2
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRRESULT2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Short getAprresult2() {
        return aprresult2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRRESULT2
     *
     * @param aprresult2 the value for YLJZN.JZ_CHRONICAPPROVE.APRRESULT2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprresult2(Short aprresult2) {
        this.aprresult2 = aprresult2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRIDEA2
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRIDEA2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getApridea2() {
        return apridea2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRIDEA2
     *
     * @param apridea2 the value for YLJZN.JZ_CHRONICAPPROVE.APRIDEA2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setApridea2(String apridea2) {
        this.apridea2 = apridea2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRTIME2
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRTIME2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Date getAprtime2() {
        return aprtime2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRTIME2
     *
     * @param aprtime2 the value for YLJZN.JZ_CHRONICAPPROVE.APRTIME2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprtime2(Date aprtime2) {
        this.aprtime2 = aprtime2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRPERSON2
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRPERSON2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getAprperson2() {
        return aprperson2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRPERSON2
     *
     * @param aprperson2 the value for YLJZN.JZ_CHRONICAPPROVE.APRPERSON2
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprperson2(String aprperson2) {
        this.aprperson2 = aprperson2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRRESULT3
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRRESULT3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Short getAprresult3() {
        return aprresult3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRRESULT3
     *
     * @param aprresult3 the value for YLJZN.JZ_CHRONICAPPROVE.APRRESULT3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprresult3(Short aprresult3) {
        this.aprresult3 = aprresult3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRIDEA3
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRIDEA3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getApridea3() {
        return apridea3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRIDEA3
     *
     * @param apridea3 the value for YLJZN.JZ_CHRONICAPPROVE.APRIDEA3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setApridea3(String apridea3) {
        this.apridea3 = apridea3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRTIME3
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRTIME3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Date getAprtime3() {
        return aprtime3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRTIME3
     *
     * @param aprtime3 the value for YLJZN.JZ_CHRONICAPPROVE.APRTIME3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprtime3(Date aprtime3) {
        this.aprtime3 = aprtime3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRPERSON3
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRPERSON3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getAprperson3() {
        return aprperson3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRPERSON3
     *
     * @param aprperson3 the value for YLJZN.JZ_CHRONICAPPROVE.APRPERSON3
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprperson3(String aprperson3) {
        this.aprperson3 = aprperson3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRLEVEL
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.APRLEVEL
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Short getAprlevel() {
        return aprlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.APRLEVEL
     *
     * @param aprlevel the value for YLJZN.JZ_CHRONICAPPROVE.APRLEVEL
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setAprlevel(Short aprlevel) {
        this.aprlevel = aprlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.MEMBER_ID
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.MEMBER_ID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.MEMBER_ID
     *
     * @param memberId the value for YLJZN.JZ_CHRONICAPPROVE.MEMBER_ID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.MEMBER_TYPE
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.MEMBER_TYPE
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.MEMBER_TYPE
     *
     * @param memberType the value for YLJZN.JZ_CHRONICAPPROVE.MEMBER_TYPE
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.CANCELIDEA
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.CANCELIDEA
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getCancelidea() {
        return cancelidea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.CANCELIDEA
     *
     * @param cancelidea the value for YLJZN.JZ_CHRONICAPPROVE.CANCELIDEA
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setCancelidea(String cancelidea) {
        this.cancelidea = cancelidea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.CANCELTIME
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.CANCELTIME
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public Date getCanceltime() {
        return canceltime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.CANCELTIME
     *
     * @param canceltime the value for YLJZN.JZ_CHRONICAPPROVE.CANCELTIME
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setCanceltime(Date canceltime) {
        this.canceltime = canceltime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.ENTITYS
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.ENTITYS
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getEntitys() {
        return entitys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.ENTITYS
     *
     * @param entitys the value for YLJZN.JZ_CHRONICAPPROVE.ENTITYS
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setEntitys(String entitys) {
        this.entitys = entitys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.ENTITYVAL
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.ENTITYVAL
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getEntityval() {
        return entityval;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.ENTITYVAL
     *
     * @param entityval the value for YLJZN.JZ_CHRONICAPPROVE.ENTITYVAL
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setEntityval(String entityval) {
        this.entityval = entityval;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.PAPERID
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.PAPERID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.PAPERID
     *
     * @param paperid the value for YLJZN.JZ_CHRONICAPPROVE.PAPERID
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setPaperid(String paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.AREA
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.AREA
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.AREA
     *
     * @param area the value for YLJZN.JZ_CHRONICAPPROVE.AREA
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.YW
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.YW
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getYw() {
        return yw;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.YW
     *
     * @param yw the value for YLJZN.JZ_CHRONICAPPROVE.YW
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setYw(String yw) {
        this.yw = yw;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.JZ_CHRONICAPPROVE.PS
     *
     * @return the value of YLJZN.JZ_CHRONICAPPROVE.PS
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public String getPs() {
        return ps;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.JZ_CHRONICAPPROVE.PS
     *
     * @param ps the value for YLJZN.JZ_CHRONICAPPROVE.PS
     *
     * @ibatorgenerated Mon Oct 27 15:50:27 CST 2014
     */
    public void setPs(String ps) {
        this.ps = ps;
    }
}