package com.medical.model;

import java.math.BigDecimal;
import java.util.Date;

public class JzManual {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.MANUAL_ID
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private Long manualId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.MANUALNO
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String manualno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.INVOICE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String invoice;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.FAMILYNO
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String familyno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.SSN
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String ssn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.MEMBERNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String membername;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.SEX
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String sex;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.AGE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private Integer age;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.LINKMODE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String linkmode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.ADDRESS
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String address;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.ASISTYPE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String asistype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.HOSPITALNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String hospitalname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.SICKNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String sickname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.CURRENTTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private Date currenttime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.BEGINTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private Date begintime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.ENDTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private Date endtime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.ACCOUNTPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal accountpayment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.DAYS
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private Integer days;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.PLANPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal planpayment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.PREDEPOSIT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal predeposit;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.RECDEPOSIT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal recdeposit;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.OFFICIALPAYMENT1
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal officialpayment1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.INITLINE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal initline;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.SELFSCALE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal selfscale;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.OFFICIALPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal officialpayment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.SELFMONEY
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal selfmoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.SELFALL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal selfall;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.HEALTHPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal healthpayment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.HOSPITALMONEY
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal hospitalmoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.OACCOUNTBALANCE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal oaccountbalance;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.BIGPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal bigpayment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.ACCOUNTBALANCE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal accountbalance;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.RESTPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal restpayment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.INJURYPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal injurypayment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.BEARPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private BigDecimal bearpayment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.OPERTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private Date opertime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.EMP_ID
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String empId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.CHECKSTATE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String checkstate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.FIELNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String fielname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.ASSIST_FLAG
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String assistFlag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.ASSIST_TIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private Date assistTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.IN_HOSPITALNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String inHospitalname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.JZ_MANUAL.OUT_FLAG
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	private String outFlag;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.MANUAL_ID
	 * @return  the value of YLJZN.JZ_MANUAL.MANUAL_ID
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Long getManualId() {
		return manualId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.MANUAL_ID
	 * @param manualId  the value for YLJZN.JZ_MANUAL.MANUAL_ID
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setManualId(Long manualId) {
		this.manualId = manualId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.MANUALNO
	 * @return  the value of YLJZN.JZ_MANUAL.MANUALNO
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getManualno() {
		return manualno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.MANUALNO
	 * @param manualno  the value for YLJZN.JZ_MANUAL.MANUALNO
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setManualno(String manualno) {
		this.manualno = manualno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.INVOICE
	 * @return  the value of YLJZN.JZ_MANUAL.INVOICE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getInvoice() {
		return invoice;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.INVOICE
	 * @param invoice  the value for YLJZN.JZ_MANUAL.INVOICE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setInvoice(String invoice) {
		this.invoice = invoice;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.FAMILYNO
	 * @return  the value of YLJZN.JZ_MANUAL.FAMILYNO
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getFamilyno() {
		return familyno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.FAMILYNO
	 * @param familyno  the value for YLJZN.JZ_MANUAL.FAMILYNO
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setFamilyno(String familyno) {
		this.familyno = familyno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.SSN
	 * @return  the value of YLJZN.JZ_MANUAL.SSN
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getSsn() {
		return ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.SSN
	 * @param ssn  the value for YLJZN.JZ_MANUAL.SSN
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.MEMBERNAME
	 * @return  the value of YLJZN.JZ_MANUAL.MEMBERNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getMembername() {
		return membername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.MEMBERNAME
	 * @param membername  the value for YLJZN.JZ_MANUAL.MEMBERNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setMembername(String membername) {
		this.membername = membername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.SEX
	 * @return  the value of YLJZN.JZ_MANUAL.SEX
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.SEX
	 * @param sex  the value for YLJZN.JZ_MANUAL.SEX
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.AGE
	 * @return  the value of YLJZN.JZ_MANUAL.AGE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.AGE
	 * @param age  the value for YLJZN.JZ_MANUAL.AGE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.LINKMODE
	 * @return  the value of YLJZN.JZ_MANUAL.LINKMODE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getLinkmode() {
		return linkmode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.LINKMODE
	 * @param linkmode  the value for YLJZN.JZ_MANUAL.LINKMODE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setLinkmode(String linkmode) {
		this.linkmode = linkmode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.ADDRESS
	 * @return  the value of YLJZN.JZ_MANUAL.ADDRESS
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.ADDRESS
	 * @param address  the value for YLJZN.JZ_MANUAL.ADDRESS
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.ASISTYPE
	 * @return  the value of YLJZN.JZ_MANUAL.ASISTYPE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getAsistype() {
		return asistype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.ASISTYPE
	 * @param asistype  the value for YLJZN.JZ_MANUAL.ASISTYPE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setAsistype(String asistype) {
		this.asistype = asistype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.HOSPITALNAME
	 * @return  the value of YLJZN.JZ_MANUAL.HOSPITALNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getHospitalname() {
		return hospitalname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.HOSPITALNAME
	 * @param hospitalname  the value for YLJZN.JZ_MANUAL.HOSPITALNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setHospitalname(String hospitalname) {
		this.hospitalname = hospitalname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.SICKNAME
	 * @return  the value of YLJZN.JZ_MANUAL.SICKNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getSickname() {
		return sickname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.SICKNAME
	 * @param sickname  the value for YLJZN.JZ_MANUAL.SICKNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setSickname(String sickname) {
		this.sickname = sickname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.CURRENTTIME
	 * @return  the value of YLJZN.JZ_MANUAL.CURRENTTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Date getCurrenttime() {
		return currenttime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.CURRENTTIME
	 * @param currenttime  the value for YLJZN.JZ_MANUAL.CURRENTTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setCurrenttime(Date currenttime) {
		this.currenttime = currenttime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.BEGINTIME
	 * @return  the value of YLJZN.JZ_MANUAL.BEGINTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Date getBegintime() {
		return begintime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.BEGINTIME
	 * @param begintime  the value for YLJZN.JZ_MANUAL.BEGINTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.ENDTIME
	 * @return  the value of YLJZN.JZ_MANUAL.ENDTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.ENDTIME
	 * @param endtime  the value for YLJZN.JZ_MANUAL.ENDTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.ACCOUNTPAYMENT
	 * @return  the value of YLJZN.JZ_MANUAL.ACCOUNTPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getAccountpayment() {
		return accountpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.ACCOUNTPAYMENT
	 * @param accountpayment  the value for YLJZN.JZ_MANUAL.ACCOUNTPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setAccountpayment(BigDecimal accountpayment) {
		this.accountpayment = accountpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.DAYS
	 * @return  the value of YLJZN.JZ_MANUAL.DAYS
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Integer getDays() {
		return days;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.DAYS
	 * @param days  the value for YLJZN.JZ_MANUAL.DAYS
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setDays(Integer days) {
		this.days = days;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.PLANPAYMENT
	 * @return  the value of YLJZN.JZ_MANUAL.PLANPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getPlanpayment() {
		return planpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.PLANPAYMENT
	 * @param planpayment  the value for YLJZN.JZ_MANUAL.PLANPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setPlanpayment(BigDecimal planpayment) {
		this.planpayment = planpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.PREDEPOSIT
	 * @return  the value of YLJZN.JZ_MANUAL.PREDEPOSIT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getPredeposit() {
		return predeposit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.PREDEPOSIT
	 * @param predeposit  the value for YLJZN.JZ_MANUAL.PREDEPOSIT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setPredeposit(BigDecimal predeposit) {
		this.predeposit = predeposit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.RECDEPOSIT
	 * @return  the value of YLJZN.JZ_MANUAL.RECDEPOSIT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getRecdeposit() {
		return recdeposit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.RECDEPOSIT
	 * @param recdeposit  the value for YLJZN.JZ_MANUAL.RECDEPOSIT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setRecdeposit(BigDecimal recdeposit) {
		this.recdeposit = recdeposit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.OFFICIALPAYMENT1
	 * @return  the value of YLJZN.JZ_MANUAL.OFFICIALPAYMENT1
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getOfficialpayment1() {
		return officialpayment1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.OFFICIALPAYMENT1
	 * @param officialpayment1  the value for YLJZN.JZ_MANUAL.OFFICIALPAYMENT1
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setOfficialpayment1(BigDecimal officialpayment1) {
		this.officialpayment1 = officialpayment1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.INITLINE
	 * @return  the value of YLJZN.JZ_MANUAL.INITLINE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getInitline() {
		return initline;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.INITLINE
	 * @param initline  the value for YLJZN.JZ_MANUAL.INITLINE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setInitline(BigDecimal initline) {
		this.initline = initline;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.SELFSCALE
	 * @return  the value of YLJZN.JZ_MANUAL.SELFSCALE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getSelfscale() {
		return selfscale;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.SELFSCALE
	 * @param selfscale  the value for YLJZN.JZ_MANUAL.SELFSCALE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setSelfscale(BigDecimal selfscale) {
		this.selfscale = selfscale;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.OFFICIALPAYMENT
	 * @return  the value of YLJZN.JZ_MANUAL.OFFICIALPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getOfficialpayment() {
		return officialpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.OFFICIALPAYMENT
	 * @param officialpayment  the value for YLJZN.JZ_MANUAL.OFFICIALPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setOfficialpayment(BigDecimal officialpayment) {
		this.officialpayment = officialpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.SELFMONEY
	 * @return  the value of YLJZN.JZ_MANUAL.SELFMONEY
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getSelfmoney() {
		return selfmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.SELFMONEY
	 * @param selfmoney  the value for YLJZN.JZ_MANUAL.SELFMONEY
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setSelfmoney(BigDecimal selfmoney) {
		this.selfmoney = selfmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.SELFALL
	 * @return  the value of YLJZN.JZ_MANUAL.SELFALL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getSelfall() {
		return selfall;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.SELFALL
	 * @param selfall  the value for YLJZN.JZ_MANUAL.SELFALL
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setSelfall(BigDecimal selfall) {
		this.selfall = selfall;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.HEALTHPAYMENT
	 * @return  the value of YLJZN.JZ_MANUAL.HEALTHPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getHealthpayment() {
		return healthpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.HEALTHPAYMENT
	 * @param healthpayment  the value for YLJZN.JZ_MANUAL.HEALTHPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setHealthpayment(BigDecimal healthpayment) {
		this.healthpayment = healthpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.HOSPITALMONEY
	 * @return  the value of YLJZN.JZ_MANUAL.HOSPITALMONEY
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getHospitalmoney() {
		return hospitalmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.HOSPITALMONEY
	 * @param hospitalmoney  the value for YLJZN.JZ_MANUAL.HOSPITALMONEY
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setHospitalmoney(BigDecimal hospitalmoney) {
		this.hospitalmoney = hospitalmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.OACCOUNTBALANCE
	 * @return  the value of YLJZN.JZ_MANUAL.OACCOUNTBALANCE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getOaccountbalance() {
		return oaccountbalance;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.OACCOUNTBALANCE
	 * @param oaccountbalance  the value for YLJZN.JZ_MANUAL.OACCOUNTBALANCE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setOaccountbalance(BigDecimal oaccountbalance) {
		this.oaccountbalance = oaccountbalance;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.BIGPAYMENT
	 * @return  the value of YLJZN.JZ_MANUAL.BIGPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getBigpayment() {
		return bigpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.BIGPAYMENT
	 * @param bigpayment  the value for YLJZN.JZ_MANUAL.BIGPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setBigpayment(BigDecimal bigpayment) {
		this.bigpayment = bigpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.ACCOUNTBALANCE
	 * @return  the value of YLJZN.JZ_MANUAL.ACCOUNTBALANCE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getAccountbalance() {
		return accountbalance;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.ACCOUNTBALANCE
	 * @param accountbalance  the value for YLJZN.JZ_MANUAL.ACCOUNTBALANCE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setAccountbalance(BigDecimal accountbalance) {
		this.accountbalance = accountbalance;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.RESTPAYMENT
	 * @return  the value of YLJZN.JZ_MANUAL.RESTPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getRestpayment() {
		return restpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.RESTPAYMENT
	 * @param restpayment  the value for YLJZN.JZ_MANUAL.RESTPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setRestpayment(BigDecimal restpayment) {
		this.restpayment = restpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.INJURYPAYMENT
	 * @return  the value of YLJZN.JZ_MANUAL.INJURYPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getInjurypayment() {
		return injurypayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.INJURYPAYMENT
	 * @param injurypayment  the value for YLJZN.JZ_MANUAL.INJURYPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setInjurypayment(BigDecimal injurypayment) {
		this.injurypayment = injurypayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.BEARPAYMENT
	 * @return  the value of YLJZN.JZ_MANUAL.BEARPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public BigDecimal getBearpayment() {
		return bearpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.BEARPAYMENT
	 * @param bearpayment  the value for YLJZN.JZ_MANUAL.BEARPAYMENT
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setBearpayment(BigDecimal bearpayment) {
		this.bearpayment = bearpayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.OPERTIME
	 * @return  the value of YLJZN.JZ_MANUAL.OPERTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Date getOpertime() {
		return opertime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.OPERTIME
	 * @param opertime  the value for YLJZN.JZ_MANUAL.OPERTIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setOpertime(Date opertime) {
		this.opertime = opertime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.EMP_ID
	 * @return  the value of YLJZN.JZ_MANUAL.EMP_ID
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.EMP_ID
	 * @param empId  the value for YLJZN.JZ_MANUAL.EMP_ID
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setEmpId(String empId) {
		this.empId = empId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.CHECKSTATE
	 * @return  the value of YLJZN.JZ_MANUAL.CHECKSTATE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getCheckstate() {
		return checkstate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.CHECKSTATE
	 * @param checkstate  the value for YLJZN.JZ_MANUAL.CHECKSTATE
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setCheckstate(String checkstate) {
		this.checkstate = checkstate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.FIELNAME
	 * @return  the value of YLJZN.JZ_MANUAL.FIELNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getFielname() {
		return fielname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.FIELNAME
	 * @param fielname  the value for YLJZN.JZ_MANUAL.FIELNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setFielname(String fielname) {
		this.fielname = fielname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.ASSIST_FLAG
	 * @return  the value of YLJZN.JZ_MANUAL.ASSIST_FLAG
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getAssistFlag() {
		return assistFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.ASSIST_FLAG
	 * @param assistFlag  the value for YLJZN.JZ_MANUAL.ASSIST_FLAG
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setAssistFlag(String assistFlag) {
		this.assistFlag = assistFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.ASSIST_TIME
	 * @return  the value of YLJZN.JZ_MANUAL.ASSIST_TIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public Date getAssistTime() {
		return assistTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.ASSIST_TIME
	 * @param assistTime  the value for YLJZN.JZ_MANUAL.ASSIST_TIME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setAssistTime(Date assistTime) {
		this.assistTime = assistTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.IN_HOSPITALNAME
	 * @return  the value of YLJZN.JZ_MANUAL.IN_HOSPITALNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getInHospitalname() {
		return inHospitalname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.IN_HOSPITALNAME
	 * @param inHospitalname  the value for YLJZN.JZ_MANUAL.IN_HOSPITALNAME
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setInHospitalname(String inHospitalname) {
		this.inHospitalname = inHospitalname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.JZ_MANUAL.OUT_FLAG
	 * @return  the value of YLJZN.JZ_MANUAL.OUT_FLAG
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public String getOutFlag() {
		return outFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.JZ_MANUAL.OUT_FLAG
	 * @param outFlag  the value for YLJZN.JZ_MANUAL.OUT_FLAG
	 * @ibatorgenerated  Thu Jan 07 16:22:31 CST 2010
	 */
	public void setOutFlag(String outFlag) {
		this.outFlag = outFlag;
	}
}