package com.medical.model;

import java.util.Date;
import java.math.BigDecimal;

public class MemberBaseinfo {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.MEMBER_ID
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String memberId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.MEMBERNAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String membername;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.PAPERID
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String paperid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.SSN
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String ssn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.FAMILYNO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String familyno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.ISYBSQDB
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private BigDecimal isybsqdb;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.RELMASTER
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String relmaster;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.SEX
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String sex;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.MASTER_NAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String masterName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.BIRTHDAY
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private Date birthday;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.HEALTH
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String health;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.SICKENTYPE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String sickentype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.SICKENNAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String sickenname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.DEFORMITY
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String deformity;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.DEFGRADE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String defgrade;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.RPRKIND
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String rprkind;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.RPRTYPE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String rprtype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.RPRADDRESS
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String rpraddress;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.LINKMODE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String linkmode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.ADDRESS
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String address;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.PERSONSTATE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String personstate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.ASSIST_TYPE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String assistType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.ASSISTCARDID
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String assistcardid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.DS
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String ds;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.AN_FILENAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String anFilename;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.ON_NO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private String onNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.MEMBER_BASEINFO.ASORT
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	private BigDecimal asort;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.MEMBER_ID
	 * @return  the value of YLJZN.MEMBER_BASEINFO.MEMBER_ID
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.MEMBER_ID
	 * @param memberId  the value for YLJZN.MEMBER_BASEINFO.MEMBER_ID
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.MEMBERNAME
	 * @return  the value of YLJZN.MEMBER_BASEINFO.MEMBERNAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getMembername() {
		return membername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.MEMBERNAME
	 * @param membername  the value for YLJZN.MEMBER_BASEINFO.MEMBERNAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setMembername(String membername) {
		this.membername = membername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.PAPERID
	 * @return  the value of YLJZN.MEMBER_BASEINFO.PAPERID
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getPaperid() {
		return paperid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.PAPERID
	 * @param paperid  the value for YLJZN.MEMBER_BASEINFO.PAPERID
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setPaperid(String paperid) {
		this.paperid = paperid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.SSN
	 * @return  the value of YLJZN.MEMBER_BASEINFO.SSN
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getSsn() {
		return ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.SSN
	 * @param ssn  the value for YLJZN.MEMBER_BASEINFO.SSN
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.FAMILYNO
	 * @return  the value of YLJZN.MEMBER_BASEINFO.FAMILYNO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getFamilyno() {
		return familyno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.FAMILYNO
	 * @param familyno  the value for YLJZN.MEMBER_BASEINFO.FAMILYNO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setFamilyno(String familyno) {
		this.familyno = familyno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.ISYBSQDB
	 * @return  the value of YLJZN.MEMBER_BASEINFO.ISYBSQDB
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public BigDecimal getIsybsqdb() {
		return isybsqdb;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.ISYBSQDB
	 * @param isybsqdb  the value for YLJZN.MEMBER_BASEINFO.ISYBSQDB
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setIsybsqdb(BigDecimal isybsqdb) {
		this.isybsqdb = isybsqdb;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.RELMASTER
	 * @return  the value of YLJZN.MEMBER_BASEINFO.RELMASTER
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getRelmaster() {
		return relmaster;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.RELMASTER
	 * @param relmaster  the value for YLJZN.MEMBER_BASEINFO.RELMASTER
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setRelmaster(String relmaster) {
		this.relmaster = relmaster;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.SEX
	 * @return  the value of YLJZN.MEMBER_BASEINFO.SEX
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.SEX
	 * @param sex  the value for YLJZN.MEMBER_BASEINFO.SEX
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.MASTER_NAME
	 * @return  the value of YLJZN.MEMBER_BASEINFO.MASTER_NAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getMasterName() {
		return masterName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.MASTER_NAME
	 * @param masterName  the value for YLJZN.MEMBER_BASEINFO.MASTER_NAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setMasterName(String masterName) {
		this.masterName = masterName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.BIRTHDAY
	 * @return  the value of YLJZN.MEMBER_BASEINFO.BIRTHDAY
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.BIRTHDAY
	 * @param birthday  the value for YLJZN.MEMBER_BASEINFO.BIRTHDAY
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.HEALTH
	 * @return  the value of YLJZN.MEMBER_BASEINFO.HEALTH
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getHealth() {
		return health;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.HEALTH
	 * @param health  the value for YLJZN.MEMBER_BASEINFO.HEALTH
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setHealth(String health) {
		this.health = health;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.SICKENTYPE
	 * @return  the value of YLJZN.MEMBER_BASEINFO.SICKENTYPE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getSickentype() {
		return sickentype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.SICKENTYPE
	 * @param sickentype  the value for YLJZN.MEMBER_BASEINFO.SICKENTYPE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setSickentype(String sickentype) {
		this.sickentype = sickentype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.SICKENNAME
	 * @return  the value of YLJZN.MEMBER_BASEINFO.SICKENNAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getSickenname() {
		return sickenname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.SICKENNAME
	 * @param sickenname  the value for YLJZN.MEMBER_BASEINFO.SICKENNAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setSickenname(String sickenname) {
		this.sickenname = sickenname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.DEFORMITY
	 * @return  the value of YLJZN.MEMBER_BASEINFO.DEFORMITY
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getDeformity() {
		return deformity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.DEFORMITY
	 * @param deformity  the value for YLJZN.MEMBER_BASEINFO.DEFORMITY
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setDeformity(String deformity) {
		this.deformity = deformity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.DEFGRADE
	 * @return  the value of YLJZN.MEMBER_BASEINFO.DEFGRADE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getDefgrade() {
		return defgrade;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.DEFGRADE
	 * @param defgrade  the value for YLJZN.MEMBER_BASEINFO.DEFGRADE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setDefgrade(String defgrade) {
		this.defgrade = defgrade;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.RPRKIND
	 * @return  the value of YLJZN.MEMBER_BASEINFO.RPRKIND
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getRprkind() {
		return rprkind;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.RPRKIND
	 * @param rprkind  the value for YLJZN.MEMBER_BASEINFO.RPRKIND
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setRprkind(String rprkind) {
		this.rprkind = rprkind;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.RPRTYPE
	 * @return  the value of YLJZN.MEMBER_BASEINFO.RPRTYPE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getRprtype() {
		return rprtype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.RPRTYPE
	 * @param rprtype  the value for YLJZN.MEMBER_BASEINFO.RPRTYPE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setRprtype(String rprtype) {
		this.rprtype = rprtype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.RPRADDRESS
	 * @return  the value of YLJZN.MEMBER_BASEINFO.RPRADDRESS
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getRpraddress() {
		return rpraddress;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.RPRADDRESS
	 * @param rpraddress  the value for YLJZN.MEMBER_BASEINFO.RPRADDRESS
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setRpraddress(String rpraddress) {
		this.rpraddress = rpraddress;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.LINKMODE
	 * @return  the value of YLJZN.MEMBER_BASEINFO.LINKMODE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getLinkmode() {
		return linkmode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.LINKMODE
	 * @param linkmode  the value for YLJZN.MEMBER_BASEINFO.LINKMODE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setLinkmode(String linkmode) {
		this.linkmode = linkmode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.ADDRESS
	 * @return  the value of YLJZN.MEMBER_BASEINFO.ADDRESS
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.ADDRESS
	 * @param address  the value for YLJZN.MEMBER_BASEINFO.ADDRESS
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.PERSONSTATE
	 * @return  the value of YLJZN.MEMBER_BASEINFO.PERSONSTATE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getPersonstate() {
		return personstate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.PERSONSTATE
	 * @param personstate  the value for YLJZN.MEMBER_BASEINFO.PERSONSTATE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setPersonstate(String personstate) {
		this.personstate = personstate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.ASSIST_TYPE
	 * @return  the value of YLJZN.MEMBER_BASEINFO.ASSIST_TYPE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getAssistType() {
		return assistType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.ASSIST_TYPE
	 * @param assistType  the value for YLJZN.MEMBER_BASEINFO.ASSIST_TYPE
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setAssistType(String assistType) {
		this.assistType = assistType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.ASSISTCARDID
	 * @return  the value of YLJZN.MEMBER_BASEINFO.ASSISTCARDID
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getAssistcardid() {
		return assistcardid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.ASSISTCARDID
	 * @param assistcardid  the value for YLJZN.MEMBER_BASEINFO.ASSISTCARDID
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setAssistcardid(String assistcardid) {
		this.assistcardid = assistcardid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.DS
	 * @return  the value of YLJZN.MEMBER_BASEINFO.DS
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getDs() {
		return ds;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.DS
	 * @param ds  the value for YLJZN.MEMBER_BASEINFO.DS
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setDs(String ds) {
		this.ds = ds;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.AN_FILENAME
	 * @return  the value of YLJZN.MEMBER_BASEINFO.AN_FILENAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getAnFilename() {
		return anFilename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.AN_FILENAME
	 * @param anFilename  the value for YLJZN.MEMBER_BASEINFO.AN_FILENAME
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setAnFilename(String anFilename) {
		this.anFilename = anFilename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.ON_NO
	 * @return  the value of YLJZN.MEMBER_BASEINFO.ON_NO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public String getOnNo() {
		return onNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.ON_NO
	 * @param onNo  the value for YLJZN.MEMBER_BASEINFO.ON_NO
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setOnNo(String onNo) {
		this.onNo = onNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.MEMBER_BASEINFO.ASORT
	 * @return  the value of YLJZN.MEMBER_BASEINFO.ASORT
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public BigDecimal getAsort() {
		return asort;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.MEMBER_BASEINFO.ASORT
	 * @param asort  the value for YLJZN.MEMBER_BASEINFO.ASORT
	 * @ibatorgenerated  Sun May 06 12:20:01 CST 2012
	 */
	public void setAsort(BigDecimal asort) {
		this.asort = asort;
	}
}