package com.medical.model;

import java.math.BigDecimal;

public class SysTOrganization {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.SYS_T_ORGANIZATION.ORGANIZATION_ID
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    private String organizationId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.SYS_T_ORGANIZATION.SERIALNUMBER
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    private String serialnumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.SYS_T_ORGANIZATION.ASORGNAME
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    private String asorgname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.SYS_T_ORGANIZATION.FULLNAME
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    private String fullname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.SYS_T_ORGANIZATION.PARENTORGID
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    private String parentorgid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.SYS_T_ORGANIZATION.DEPTH
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    private BigDecimal depth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.SYS_T_ORGANIZATION.STATUS
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    private String status;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.SYS_T_ORGANIZATION.ORGANIZATION_ID
     *
     * @return the value of YLJZN.SYS_T_ORGANIZATION.ORGANIZATION_ID
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.SYS_T_ORGANIZATION.ORGANIZATION_ID
     *
     * @param organizationId the value for YLJZN.SYS_T_ORGANIZATION.ORGANIZATION_ID
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.SYS_T_ORGANIZATION.SERIALNUMBER
     *
     * @return the value of YLJZN.SYS_T_ORGANIZATION.SERIALNUMBER
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public String getSerialnumber() {
        return serialnumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.SYS_T_ORGANIZATION.SERIALNUMBER
     *
     * @param serialnumber the value for YLJZN.SYS_T_ORGANIZATION.SERIALNUMBER
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.SYS_T_ORGANIZATION.ASORGNAME
     *
     * @return the value of YLJZN.SYS_T_ORGANIZATION.ASORGNAME
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public String getAsorgname() {
        return asorgname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.SYS_T_ORGANIZATION.ASORGNAME
     *
     * @param asorgname the value for YLJZN.SYS_T_ORGANIZATION.ASORGNAME
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public void setAsorgname(String asorgname) {
        this.asorgname = asorgname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.SYS_T_ORGANIZATION.FULLNAME
     *
     * @return the value of YLJZN.SYS_T_ORGANIZATION.FULLNAME
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.SYS_T_ORGANIZATION.FULLNAME
     *
     * @param fullname the value for YLJZN.SYS_T_ORGANIZATION.FULLNAME
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.SYS_T_ORGANIZATION.PARENTORGID
     *
     * @return the value of YLJZN.SYS_T_ORGANIZATION.PARENTORGID
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public String getParentorgid() {
        return parentorgid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.SYS_T_ORGANIZATION.PARENTORGID
     *
     * @param parentorgid the value for YLJZN.SYS_T_ORGANIZATION.PARENTORGID
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public void setParentorgid(String parentorgid) {
        this.parentorgid = parentorgid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.SYS_T_ORGANIZATION.DEPTH
     *
     * @return the value of YLJZN.SYS_T_ORGANIZATION.DEPTH
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public BigDecimal getDepth() {
        return depth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.SYS_T_ORGANIZATION.DEPTH
     *
     * @param depth the value for YLJZN.SYS_T_ORGANIZATION.DEPTH
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public void setDepth(BigDecimal depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.SYS_T_ORGANIZATION.STATUS
     *
     * @return the value of YLJZN.SYS_T_ORGANIZATION.STATUS
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.SYS_T_ORGANIZATION.STATUS
     *
     * @param status the value for YLJZN.SYS_T_ORGANIZATION.STATUS
     *
     * @ibatorgenerated Wed Aug 12 11:56:50 CST 2009
     */
    public void setStatus(String status) {
        this.status = status;
    }
}