package com.medical.model;

import java.util.Date;

public class TestSsn {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.TEST_SSN.T_ID
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    private String tId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.TEST_SSN.MEMBER_ID
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    private String memberId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.TEST_SSN.SSN1
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    private String ssn1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.TEST_SSN.SSN2
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    private String ssn2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.TEST_SSN.SSN3
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    private String ssn3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.TEST_SSN.CTIME
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    private Date ctime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.TEST_SSN.UTIME
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    private Date utime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column YLJZN.TEST_SSN.DS
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    private String ds;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.TEST_SSN.T_ID
     *
     * @return the value of YLJZN.TEST_SSN.T_ID
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.TEST_SSN.T_ID
     *
     * @param tId the value for YLJZN.TEST_SSN.T_ID
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void settId(String tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.TEST_SSN.MEMBER_ID
     *
     * @return the value of YLJZN.TEST_SSN.MEMBER_ID
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.TEST_SSN.MEMBER_ID
     *
     * @param memberId the value for YLJZN.TEST_SSN.MEMBER_ID
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.TEST_SSN.SSN1
     *
     * @return the value of YLJZN.TEST_SSN.SSN1
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public String getSsn1() {
        return ssn1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.TEST_SSN.SSN1
     *
     * @param ssn1 the value for YLJZN.TEST_SSN.SSN1
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void setSsn1(String ssn1) {
        this.ssn1 = ssn1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.TEST_SSN.SSN2
     *
     * @return the value of YLJZN.TEST_SSN.SSN2
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public String getSsn2() {
        return ssn2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.TEST_SSN.SSN2
     *
     * @param ssn2 the value for YLJZN.TEST_SSN.SSN2
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void setSsn2(String ssn2) {
        this.ssn2 = ssn2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.TEST_SSN.SSN3
     *
     * @return the value of YLJZN.TEST_SSN.SSN3
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public String getSsn3() {
        return ssn3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.TEST_SSN.SSN3
     *
     * @param ssn3 the value for YLJZN.TEST_SSN.SSN3
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void setSsn3(String ssn3) {
        this.ssn3 = ssn3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.TEST_SSN.CTIME
     *
     * @return the value of YLJZN.TEST_SSN.CTIME
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.TEST_SSN.CTIME
     *
     * @param ctime the value for YLJZN.TEST_SSN.CTIME
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.TEST_SSN.UTIME
     *
     * @return the value of YLJZN.TEST_SSN.UTIME
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.TEST_SSN.UTIME
     *
     * @param utime the value for YLJZN.TEST_SSN.UTIME
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column YLJZN.TEST_SSN.DS
     *
     * @return the value of YLJZN.TEST_SSN.DS
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public String getDs() {
        return ds;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column YLJZN.TEST_SSN.DS
     *
     * @param ds the value for YLJZN.TEST_SSN.DS
     *
     * @ibatorgenerated Thu Oct 23 20:48:13 CST 2014
     */
    public void setDs(String ds) {
        this.ds = ds;
    }
}