package com.medical.model;

import java.math.BigDecimal;
import java.util.Date;

public class VbSearchinfo {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.MEMBERNAME
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private String membername;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.FAMILYNO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private String familyno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.SSN
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private String ssn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.PAPERID
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private String paperid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.BEGIN_DATE
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private Date beginDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.HOSPITAL_ID
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private String hospitalId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.HOSPITAL_NAME
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private String hospitalName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.FIN_DATE
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private Date finDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.DIAGNOSE_NAME
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private String diagnoseName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.ALLMONEY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private BigDecimal allmoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.ASSIST_TYPE
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private String assistType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.OUT_FLAG
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private Short outFlag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.PERSONPAY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private BigDecimal personpay;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.ASSISTPAY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private BigDecimal assistpay;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column YLJZN.VB_SEARCHINFO.INSURANCEPAY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	private BigDecimal insurancepay;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.MEMBERNAME
	 * @return  the value of YLJZN.VB_SEARCHINFO.MEMBERNAME
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public String getMembername() {
		return membername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.MEMBERNAME
	 * @param membername  the value for YLJZN.VB_SEARCHINFO.MEMBERNAME
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setMembername(String membername) {
		this.membername = membername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.FAMILYNO
	 * @return  the value of YLJZN.VB_SEARCHINFO.FAMILYNO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public String getFamilyno() {
		return familyno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.FAMILYNO
	 * @param familyno  the value for YLJZN.VB_SEARCHINFO.FAMILYNO
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setFamilyno(String familyno) {
		this.familyno = familyno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.SSN
	 * @return  the value of YLJZN.VB_SEARCHINFO.SSN
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public String getSsn() {
		return ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.SSN
	 * @param ssn  the value for YLJZN.VB_SEARCHINFO.SSN
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.PAPERID
	 * @return  the value of YLJZN.VB_SEARCHINFO.PAPERID
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public String getPaperid() {
		return paperid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.PAPERID
	 * @param paperid  the value for YLJZN.VB_SEARCHINFO.PAPERID
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setPaperid(String paperid) {
		this.paperid = paperid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.BEGIN_DATE
	 * @return  the value of YLJZN.VB_SEARCHINFO.BEGIN_DATE
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public Date getBeginDate() {
		return beginDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.BEGIN_DATE
	 * @param beginDate  the value for YLJZN.VB_SEARCHINFO.BEGIN_DATE
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.HOSPITAL_ID
	 * @return  the value of YLJZN.VB_SEARCHINFO.HOSPITAL_ID
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.HOSPITAL_ID
	 * @param hospitalId  the value for YLJZN.VB_SEARCHINFO.HOSPITAL_ID
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.HOSPITAL_NAME
	 * @return  the value of YLJZN.VB_SEARCHINFO.HOSPITAL_NAME
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public String getHospitalName() {
		return hospitalName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.HOSPITAL_NAME
	 * @param hospitalName  the value for YLJZN.VB_SEARCHINFO.HOSPITAL_NAME
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.FIN_DATE
	 * @return  the value of YLJZN.VB_SEARCHINFO.FIN_DATE
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public Date getFinDate() {
		return finDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.FIN_DATE
	 * @param finDate  the value for YLJZN.VB_SEARCHINFO.FIN_DATE
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setFinDate(Date finDate) {
		this.finDate = finDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.DIAGNOSE_NAME
	 * @return  the value of YLJZN.VB_SEARCHINFO.DIAGNOSE_NAME
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public String getDiagnoseName() {
		return diagnoseName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.DIAGNOSE_NAME
	 * @param diagnoseName  the value for YLJZN.VB_SEARCHINFO.DIAGNOSE_NAME
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setDiagnoseName(String diagnoseName) {
		this.diagnoseName = diagnoseName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.ALLMONEY
	 * @return  the value of YLJZN.VB_SEARCHINFO.ALLMONEY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public BigDecimal getAllmoney() {
		return allmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.ALLMONEY
	 * @param allmoney  the value for YLJZN.VB_SEARCHINFO.ALLMONEY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setAllmoney(BigDecimal allmoney) {
		this.allmoney = allmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.ASSIST_TYPE
	 * @return  the value of YLJZN.VB_SEARCHINFO.ASSIST_TYPE
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public String getAssistType() {
		return assistType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.ASSIST_TYPE
	 * @param assistType  the value for YLJZN.VB_SEARCHINFO.ASSIST_TYPE
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setAssistType(String assistType) {
		this.assistType = assistType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.OUT_FLAG
	 * @return  the value of YLJZN.VB_SEARCHINFO.OUT_FLAG
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public Short getOutFlag() {
		return outFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.OUT_FLAG
	 * @param outFlag  the value for YLJZN.VB_SEARCHINFO.OUT_FLAG
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setOutFlag(Short outFlag) {
		this.outFlag = outFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.PERSONPAY
	 * @return  the value of YLJZN.VB_SEARCHINFO.PERSONPAY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public BigDecimal getPersonpay() {
		return personpay;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.PERSONPAY
	 * @param personpay  the value for YLJZN.VB_SEARCHINFO.PERSONPAY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setPersonpay(BigDecimal personpay) {
		this.personpay = personpay;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.ASSISTPAY
	 * @return  the value of YLJZN.VB_SEARCHINFO.ASSISTPAY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public BigDecimal getAssistpay() {
		return assistpay;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.ASSISTPAY
	 * @param assistpay  the value for YLJZN.VB_SEARCHINFO.ASSISTPAY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setAssistpay(BigDecimal assistpay) {
		this.assistpay = assistpay;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column YLJZN.VB_SEARCHINFO.INSURANCEPAY
	 * @return  the value of YLJZN.VB_SEARCHINFO.INSURANCEPAY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public BigDecimal getInsurancepay() {
		return insurancepay;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column YLJZN.VB_SEARCHINFO.INSURANCEPAY
	 * @param insurancepay  the value for YLJZN.VB_SEARCHINFO.INSURANCEPAY
	 * @ibatorgenerated  Fri May 14 16:08:59 CST 2010
	 */
	public void setInsurancepay(BigDecimal insurancepay) {
		this.insurancepay = insurancepay;
	}
}